### ISSUE TITLE
Digital Credentials

### ISSUE THREAD

**Issue by RByers** [mozilla/standards-positions#1003]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Digital Credentials
* Specification or proposal URL (if available): https://wicg.github.io/digital-identities/
* Explainer URL (if available): https://github.com/WICG/digital-identities/blob/main/proposals/identity-credential-proposal.md (to be updated - but still mostly accurate)
* Proposal author(s) (`@`-mention GitHub accounts): @marcoscaceres @samuelgoto
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @bvandersloot-mozilla @martinthomson

### Other information

The online digital credential space is complex space with lots of pieces, lots of uncertainty still, and perhaps a set of non-standardized browser-specific design properties. I think the useful review of this API is within the larger context and how having a browser API may make things better and/or worse, and the conditions (if any) under which Mozilla would be supportive of seeing this API added to the web. One possible useful resource is [this talk I gave to PING at TPAC](https://docs.google.com/presentation/u/1/d/1Z7blMTME1tAQAdO-Wr42oVNN3CRIbklASjbJdB1JYOc/edit?resourcekey=0-ockU2NbemVbLEeF94-peNA#slide=id.g1e7061371dc_1_5).

**Comment by martinthomson** [comment]
@RByers, the specification is pretty skeletal.  I'm confident that I could NOT implement anything from that.  The explainer has a banner saying that it isn't valid.  What is going on with the proposal?

**Comment by RByers** [comment]
Yep, this is far from ready to ship but we do feel we're close to being able to do an origin trial, so I wanted to at least start this discussion. We're working on an updated explainer now which we should have posted in a week or so. It's fine with me if you say you can't form a standards position until the spec is more complete, including a more detailed security and privacy considerations section.

**Comment by martinthomson** [comment]
You got it.  The issues that [WebKit raise](https://github.com/WebKit/standards-positions/issues/332#issuecomment-2019400609) also give us pause.  Enough so that I'd personally be inclined to say "negative", especially given the current state of the documentation.  Has there been any effort to mitigate those concerns?  Shipping an origin trial isn't exactly going to help there.

**Comment by martinthomson** [comment]
The [digital credentials API](https://wicg.github.io/digital-identities/) is an extension to the [credential management API](https://w3c.github.io/webappsec-credential-management/) that enables access to identity documentation that might be held in the user agent or a wallet on the same device.

We broadly agree with the [concerns raised by the WebKit team](https://github.com/WebKit/standards-positions/issues/332#issuecomment-2019400609), though we consider some of these to be significant enough to instead regard this proposal as negative. We observe some effort to mitigate these risks, but we are not confident that these will be successful in producing an unconditionally positive outcome. Additionally, our analysis revealed a privacy concern around the potential use of selective disclosure in the API.

A Web that follows [our principles](https://www.mozilla.org/en-US/about/webvision/full/) respects an individual’s choice about the identity they present to others. This is an essential part of making the Web a [safe](https://www.mozilla.org/en-US/about/webvision/full/#safety) place for [everyone](https://w3ctag.github.io/ethical-web-principles/#allpeople). Credentials offered by governments and similar entities generally do not recognize this aspect of identity.
The potential that requests for digital credentials might become an expected part of online interactions exists and could damage this important characteristic of the Web. There are very few online interactions where providing identity is truly necessary, but many where sites (and governments) might prefer that the identity of a person be known. Increasing requests for identity does not mean a trivial annoyance. It could mean that people might be excluded from services and communities when they [cannot](https://www.unhcr.org/about-unhcr/who-we-protect/stateless-people) provide credentials or instead [choose](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context) to protect their privacy.

The potential for interoperability problems resulting from a proliferation of formats is particularly concerning. For people that seek to interact with government services, using identity documents in a fixed format from a single provider is likely to be acceptable. This isn’t true for a range of other services that might seek to use identity information, where limiting support for formats or providers might have the effect of unnecessarily excluding people.

We acknowledge that this style of API has superior utility to the hodgepodge of forms, QR codes, and other overlay systems that people have to navigate today when there is a genuine need to present credentials. Many people have wallets, or will get them soon, and Web integration could be far more convenient and reliable than those alternatives. We also recognize that the issuer-holder-verifier model that underpins the proposed API is a powerful tool for enabling individual autonomy, far superior to alternatives involving third party identity services. However, it is not enough to be superior to alternatives; it is essential to address risks and ensure that [new features make the web better overall](https://w3ctag.github.io/design-principles/#leave-the-web-better). We owe people a solution that acts in their interests, not just something that is justified because the alternative is worse or because it is more convenient.

The role of selective disclosure is an aspect of the overall system that is poorly understood and explored. While presenting a complete credential (a driving license or passport, say) can be readily understood to represent a total privacy break, the true privacy implications of selective disclosure are likely to be very poorly understood. The exact conditions under which selective disclosure might be engaged are not defined, which is already a problem. However, the potential for selective disclosure to be engaged without also providing unlinkability is very worrying.

There are some cases where linkability might be a desirable property, but the non-obvious privacy characteristics that result make it hard to recommend anything other than a system based on zero-knowledge proofs. Even if that were the case — and it seems like zero-knowledge solutions are unlikely to be ready in the near term — that sites are able to specify a provider makes zero-knowledge offerings risky for [the same reasons that Privacy Pass is difficult to recommend](https://blog.mozilla.org/en/privacy-security/captcha-successor-privacy-pass-has-no-easy-answers-for-online-abuse/).

Finally, we note that the proposal has too little information to implement. More work is needed.

**Comment by c2bo** [comment]
> Thank you Martin! I just want to flag here that I've heard from a couple government technology providers that they are using custom schemes instead of the digital credentials API because of Firefox support for the former but not the latter. It's hard to say to what extent this increases the risk of the EUDI ecosystem getting locked into the custom scheme architecture (thereby preventing the W3C and browsers from having an effective seat at the table in defending users from abuse), but its a risk to be aware of.

From an implementers perspective, there are still quite some uncertainties about DC API:
- Not clear if support will be added to all browsers
- Unclear if the protocols/credential formats chosen by the ecosystem will be supported/allowed by all browser

From my perspective, I would really like to have an alternative to custom schemes for the obvious security and UX benefits, but I can also understand why everyone started to build in the direction of custom schemes - it appeared like it might take some time before alternatives are fully standardized and implemented, so custom schemes appeared to be the only short-term option for wallet invocation.

Blocking right now seems like a pretty extreme reaction imho, adding some friction like a warning sounds like a middle ground that more people could live with? Such a warning could imho be especially useful once DC API is widely available and supports the functionality required by the different ecosystems (on all/most platforms) to motivate people to move away from custom schemes.

A question regarding this comment:

> We've discussed outright blocking openid4vp-schemed navigation for these reason. The idea of a scary interstitial warning sounds like a promising middle ground though; thanks for sharing that.

Would this statement hold true for all custom schemes for wallet-invocation that are currently being defined/used, e.g., also `mdoc://` as defined in ISO 18013-7?
