### ISSUE TITLE
MediaStreamTrack Content Hints

### ISSUE THREAD

**Issue by alvestrand** [mozilla/standards-positions#101]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: MediaStreamTrack Content Hints
* Specification or proposal URL: https://w3c.github.io/mst-content-hint/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): jan-ivar

**Comment by annevk** [comment]
cc @jan-ivar

**Comment by jan-ivar** [comment]
Sorry @nils-ohlmeier for taking a while to collect my thoughts. I have several concerns with this API.

### Weak API

It's an odd control surface. It doesn't feel like a control surface.

This is a JS app telling the browser something, and expecting functionality in return, yet it doesn't appear to provide any normative language that a browser MUST do anything in response, which seems weak. It's only a "hint" and not "type", right? (If I'm mistaken, then the API seems to a bit of a misnomer).

# Action at a distance.

It feels like a control surface masquerading as a property, or a message channel: "To whomever finds this note..."—It's a lateral API attempting to influence (control?) multiple sinks, potentially at the same time. Maybe. Playback? PeerConnection? MediaRecorder? element.captureStream? AudioContext.createMediaStreamSource()?

In WebRTC, we rejected `pc.addStream` over this; it was deemed undesirable to control a PeerConnection implicitly through a MediaStream, and how many tracks were in it.

### Permanence issues

These hints don't make it through a peer connection, web audio, `element.captureStream()` or any other modifications, right?—JS will have to stick these hints back on the track like post-it notes that keep falling off.

### Under-specified

* How should browsers behave if the JS twiddles the bit live over time?
* How does it work with track.clone()? Can each clone have its own value? 

The spec doesn't say.

### Redundancy and confusion over conflicts

There seems to be significant overlap with existing control surface APIs, like `pc.setParameters()` and
`applyConstraints({echoCancellation, noiseSuppression, autoGainControl})`.

This can lead to conflict or at least confusion over net behavior.

This all combines into a bit of a "throw salt over your shoulder" API for me. Line up all the rocks and wave the sticks right, and maybe the planes will land, or at least some will, maybe not all.

I think we're better off closing any functionality gap in existing APIs, instead of introducing a competing API.

**Comment by nils-ohlmeier** [comment]
After looking at @jan-ivar review and some more internal discussion I think we should be saying "defer" to this as we don't consider JS giving hints is the right solution to the problem.

**Comment by jan-ivar** [comment]
After talking with @nils-ohlmeier some more, and looking at [our dashboard](https://mozilla.github.io/standards-positions/) we seem to be using "non-harmful" for things of a nature similar to this. The lone place we use "defer" the accompanying description uses the word "dangerous". Kudos to @nils-ohlmeier who originally adjusted for this, where I didn't.

**Comment by jan-ivar** [comment]
I've filed an objection with more detail about [changes I think are needed](https://lists.w3.org/Archives/Public/public-webrtc/2019Aug/0022.html) for us to reconsider this position.

**Comment by jan-ivar** [comment]
There's been progress on issues filed (https://github.com/w3c/mst-content-hint/issues/28, https://github.com/w3c/mst-content-hint/issues/33).

Also, `degradationPreference` which was dropped from WebRTC 1.0 was moved here for organizational reasons (overlapping control surface).

As a result, I agree it is now "worth prototyping" https://github.com/mozilla/standards-positions/issues/101#issuecomment-442702021 and am [supportive](https://lists.w3.org/Archives/Public/public-webrtc/2020Feb/0072.html).

**Comment by annevk** [comment]
@jan-ivar could you create a PR to that effect?
