### ISSUE TITLE
site bug: Can't expand detail section after search

### ISSUE THREAD

**Issue by Trikolon** [mozilla/standards-positions#1118]
In the new version of the website after I filter the list via the search box the detail section does not expand on click anymore. See attached video for a demo.

Browser: Firefox Nightly 134.0a1 (2024-11-13) (aarch64)

https://github.com/user-attachments/assets/4f85174b-bc7b-4f32-9c54-79f46c2c7d13

**Comment by martinthomson** [comment]
I'm seeing the same issue.  You can click the link to open the details, but it won't close.

**Comment by zcorpan** [comment]
This seems to be a bug in Gecko. If *any* row in the table has `visibility: collapse`, then the `summary` element can't be clicked. (The `summary` element is positioned on top of the previous row with relative positioning.) It works fine in Chrome.

I'll work around this, since WebKit also doesn't have usable support for `visibility: collapse`, but I'll also file a bug about this issue for Gecko.
