### ISSUE TITLE
HTML Modules

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#137]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTML Modules
* Specification or proposal URL:  https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/explainer.md
* Mozillians who can provide input (optional): @annevk, @dbaron 

### Other information
Proposes "...an extension of the ES6 Script Modules system to include HTML Modules. These will allow web developers to package and access declarative content from script in a way that allows for good componentization and reusability, and integrates well into the existing ES6 Modules infrastructure."

Intent to implement in Blink:
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/i2i.md

Proposed changes to ES and HTML specs:
https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-module-spec-changes.md

Cc'ing @dandclark  @bocupp @samsebree @travisleithead from Microsoft, so they can track discussion and answer questions.

**Comment by marcoscaceres** [comment]
Updated the above with a few more folks from Microsoft, as they are all driving the design and would appreciate our feedback.

**Comment by bzbarsky** [comment]
My take at TPAC was that this seemed like a pretty nice idea.  I ran it by @jonco3 and as I recall he didn't see any obvious problems.

**Comment by annevk** [comment]
Yeah, at a high-level this seems fine and affirms we did the right thing by waiting for an ES-module-based solution rather than ship HTML Imports, but there's a [bunch of details](https://github.com/w3c/webcomponents/issues?q=is%3Aissue+is%3Aopen+label%3Amodules) that still need to be sorted.

**Comment by marcoscaceres** [comment]
@dbaron, given @annevk and @bzbarsky's comments above, could we give an official position like "worth prototyping" or "non-harmful"? 

Folks at Microsoft would like to move this into a WICG repo for incubation so they'd appreciate some positive signal support from us before doing so.

**Comment by annevk** [comment]
It seems to me this should be a PR against the HTML Standard developed with the HTML and web components community on w3c/webcomponents. Taking it to yet another venue doesn't seem great?

**Comment by marcoscaceres** [comment]
@annevk, I don't mind where it gets done - but definitely agree it would make most sense to do in in the WHATWG, given how closely tied it is to HTML. WHATWG also has a great incubation process and supportive community. 

^^^ @dandclark @BoCupp @samsebree @travisleithead

**Comment by sideshowbarker** [comment]
>> It seems to me this should be a PR against the HTML Standard developed with the HTML and web components community on w3c/webcomponents. Taking it to yet another venue doesn't seem great?
>
> @annevk, I don't mind where it gets done - but definitely agree it would make most sense to do in in the WHATWG, given how closely tied it is to HTML. WHATWG also has a great incubation process and supportive community.
> 
> ^^^ @dandclark @BoCupp @samsebree @travisleithead

I notice @ yoavweiss created https://github.com/wicg/html-modules yesterday. Was there some discussion/decision somewhere (privately?) that led to that getting created? Has there been no discussion about the proposal to instead just make it a PR against the HTML spec?

**Comment by yoavweiss** [comment]
> WHATWG also has a great incubation process

Can you expand on that process? I'd love to know more.

> I notice @yoavweiss created https://github.com/wicg/html-modules yesterday. Was there some discussion/decision somewhere (privately?)

@travisleithead [requested](https://discourse.wicg.io/t/proposal-html-modules/3309/8) for a WICG repo for the HTML modules proposal, and it seemed to get a fair amount of support, so I opened one for that purpose. I believe the venue for an incubation to happen in is at the discretion of the folks driving the incubation, assuming there's a supporting community there.

> Has there been no discussion about the proposal to instead just make it a PR against the HTML spec?

My personal experience is that having proposals live as PRs for long periods of time, especially before there's strong commitments from multiple vendors (which I think HTML modules still doesn't have), is not ideal. So I don't know if I'd recommend that route for new proposals.

Which is not to say that the proposal won't end up as an HTML PR once it gets more mature and gains multi-vendor support. It's just that IMO, it doesn't have to start there. Let me know if you think otherwise.

**Comment by annevk** [comment]
@yoavweiss https://whatwg.org/working-mode#changes. And as far as I know HTML modules does have strong support, at least within the web components community. It just lacked someone to do the work.

**Comment by yoavweiss** [comment]
> And as far as I know HTML modules does have strong support, at least within the web components community. It just lacked someone to do the work.

If that means that once a PR meets the bar in the link (regarding tests, review, style) is will be merged, as it will be considered to have multi-vendor support, that SGTM. Up to @travisleithead and folks to decide if they prefer to do the incubation work as a PR or in a separate repo. Seems like https://whatwg.org/working-mode#new-proposals considers both options viable.

(Personally, I find that an independent repo can make it easier to handle issues and feedback from the broader community, have an explainer and other documentation of the use-cases, etc.)

**Comment by annevk** [comment]
We already have that repo, right? w3c/webcomponents. It also has multiple issues filed, as well as lots of discussion. What in part I find problematic is that nobody there was consulted about this.

**Comment by travisleithead** [comment]
Appreciate the feedback. We're just getting our feet wet in a new process for how we [Microsoft] intend to bring a variety of new incubation ideas forward, and in general we want to be using WICG repos for every idea that gets positive customer feedback and community interest. As noted, the nature of an independent repo enables a center-of-gravity to form around the feature and we like it for that reason.

I don't feel too strong either way about incubating html modules in w3c/webcomponents. I have a slight preference for a new repo because it's already there now and also because the w3c/webcomponents repo has mainly dispersed it's previous efforts into other places, e.g., in the [readme](https://github.com/w3c/webcomponents/blob/gh-pages/README.md) it notes that web components are being developed in a variety of places, and encourages readers "to file issues in the most specific repository possible, per the above issue pointers. (It's often not this repository.)" However, we certainly didn't intend to ruffle any feathers, and if the folks at w3c/webcomponents feel strongly about developing html-modules in that repo, then that's fine with us and we'll happily move the content and issues there instead. I filed https://github.com/w3c/webcomponents/issues/794 to get folks opinion. We don't have any material content yet in wicg/html-modules, so it's not too late to make a change.

**Comment by travisleithead** [comment]
Just to close on [this](https://github.com/mozilla/standards-positions/issues/137#issuecomment-463545161)...

> I notice @yoavweiss created https://github.com/wicg/html-modules yesterday. Was there some discussion/decision somewhere (privately?) that led to that getting created? Has there been no discussion about the proposal to instead just make it a PR against the HTML spec?

Thanks for all the feedback. I've now deleted that repo, but not before migrating to the [two](https://github.com/w3c/webcomponents/issues/797) [issues](https://github.com/w3c/webcomponents/issues/798) that were filed there to w3c/webcomponents while we prepare the PR for whatwg/html.

**Comment by dbaron** [comment]
It sounds like there's sufficient consensus here to mark this as `worth prototyping`.
