### ISSUE TITLE
Contact Picker API

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#153]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Contact Picker API
* Specification or proposal URL: [Chrome Status page](https://www.chromestatus.com/feature/6511327140904960), [Repository & Explainer](https://github.com/beverloo/contact-api)
* Mozillians who can provide input (optional): @annevk @tantek (probably should add others, please @-mention)

This is something Google is working on that it would be useful for us to provide input on.

**Comment by marcoscaceres** [comment]
Safari's solution to this on Desktop is more elegant, IMO. You can still use good old HTML inputs with `autocomplete`, it requires user gesture, and safari gives you the ability to fill from a contact (even if it's just your own personal details).. and no API needed. 

<img width="299" alt="Screenshot 2019-04-25 11 02 42" src="https://user-images.githubusercontent.com/870154/56702909-cf515c00-6749-11e9-809f-67b4aa2c3b8d.png">

**Comment by marcoscaceres** [comment]
Example code:

```HTML
<input type="tel" name="home-phone" autocomplete="home tel">
<input type="email" name="home-email" autocomplete="home email">
```

Live example to try in Safari:
https://jsfiddle.net/mdtybcuq/

More extensive examples here:
https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/

**Comment by marcoscaceres** [comment]
Has a further look at the contacts API... it does provide some good privacy qualities in that it's a single-use, user-gated, proposal that would work similarly to the file picker. It also protects from oversharing by requiring the author to request what they need up-front (e.g., I need `["name", "phone"]... though these names could probably better align with HTML autocomplete).

**Comment by rayankans** [comment]
@marcoscaceres Given the progress made on the issue you filed and the discussions we had, do you have any more concerns regarding the API? If not, do you mind updating this issue?

**Comment by marcoscaceres** [comment]
I personally don't have any further concern. I wonder if the folks that were  originally tagged (@annevk and @tantek) might want  to provide additional feedback before we take a position.

**Comment by tantek** [comment]
I read and re-checked the Explainer, and frankly given the repeated past
Contacts API failures and zero mention of them in the Explainer, I’m going to deem this proposal not worth taking the time to thoroughly evaluate until the Explainer at a minimum:

1. Documents previous Contacts API standards attempts (see [https://tantek.com/2020/026/t2/](https://tantek.com/2020/026/t2/) for some links to start)
2. Provides summary explanations for their failures
3. Describes how the current proposal is different from previous proposals in such a way as to at least avoid those failures (i.e. there should be a logical chain of reasoning from identifying key differences and how those either cause or prevent different outcomes from prior attempts).

I think we should go ahead and publish a position of "defer", since a similar request to number 3 was made a whole year ago ([https://github.com/w3ctag/design-reviews/issues/337#issuecomment-460555385](https://github.com/w3ctag/design-reviews/issues/337#issuecomment-460555385)) without any subsequent respective additions to the Explainer.

Also given the critical comments in that discussion, especially from [https://github.com/torgo](https://github.com/torgo), and knowing how much more abusive social network/media "apps" have become with aggressive sign-up, spam, user-acquisition tactics in recent years, I’m leaning towards expecting an eventual "harmful" evaluation.

If the purely markup-only approaches were separated out into another proposal, I’d be more optimistic of more quickly evaluating those, and expecting browsers could implement those simpler (fewer ways to use/abuse) feature(s) in such a way that could be "worth prototyping".

(Originally published at: https://tantek.com/2020/037/t1/)

**Comment by tomayac** [comment]
There’s a [PR open](https://github.com/WICG/contact-api/pull/31) that mentions the previous attempts and describes how the current attempt is different.

**Comment by domfarolino** [comment]
In #266 @marcoscaceres [wrote](https://github.com/mozilla/standards-positions/pull/266#issuecomment-584970862):

> Will follow up in the bug if need be.

Regarding some privacy questions. It seems like Chrome is looking to ship this API, so I'm just curious if there is any more input from Mozilla, since some things seem to have been addressed.

**Comment by marcoscaceres** [comment]
I don't have anything further, but there are still some good open issues that would be nice to see addressed (they might have been, I've not followed the spec): like https://github.com/WICG/contact-api/issues/9 - will it be enabled by feature policy or exclusive to first party top-level?  

Irrespective, we are probably happy to defer and see how it plays in the wild. @domfarolino, was there an origin trial? or is it just shipping as is?

**Comment by rayankans** [comment]
> will it be enabled by feature policy or exclusive to first party top-level?

ATM it's exclusive to first party top-level, to limit potential abuse scenarios.

> was there an origin trial? or is it just shipping as is?

There was an origin trial, and the API shipped, with support for names/tel/email. There was also another origin trial for address/icon support, and now that is undergoing the process of getting shipped as well.

**Comment by marcoscaceres** [comment]
Thanks for the update @rayankans.

**Comment by marcoscaceres** [comment]
Looks like Apple is implementing the contacts API:
https://github.com/WebKit/WebKit/tree/main/Source/WebCore/Modules/contact-picker

And it's being moved into W3C DAP for standardization:
https://github.com/w3c/dap-charter/issues/97

In light of renewed implementer interest, I wonder if Mozilla may consider re-evaluating its position on this API (currently defer)?
