### ISSUE TITLE
File Handling

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#158]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: File Handling
* Specification or proposal URL: [Explainer](https://github.com/WICG/file-handling/blob/master/explainer.md), [Repository](https://github.com/WICG/file-handling)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @annevk @bzbarsky @hsivonen @dbaron 

### Other information

This proposal was just submitted for TAG review, and it seems at a high level like something I'd be interested in.  I haven't looked at the details yet.  It's still explainer-only; no spec yet.

**Comment by annevk** [comment]
So the main use case seems to be operating on OS-level files in web applications whereby the OS knows about the relevant web application due to a prior visit of the user to that application (and whatever additional restrictions are applied on top). So instead of application -> file, you can now go file -> application, as you already could with native applications.

The bits I don't like here:

* Relying on app manifest. It's not entirely clear to me that is the way to go for all things and in particular if we get Origin Policy/Manifest there might be changes here.
* Enforcing a particular kind of URL to be generated. I don't think we should force particular URLs on applications, even if it's only the query parameters (at least not beyond `./well-known/` and friends).

It seems somewhat more natural to me that a service worker is involved here and that opens the application as appropriate and forwards the file handle to the appropriate place.

**Comment by dbaron** [comment]
In #274 @annevk is proposing a `defer` position here.  I guess that's _okay_, but given that there is a good bit of activity elsewhere relating to this, e.g., in w3ctag/design-reviews#371, I tend to think it may be worth developing a real position here sooner rather than later.

**Comment by annevk** [comment]
I'm happy to keep this open until there's been another update.

The other worry I have is that creating good UI for this is hard and there might be quite bit of spam. Even with native applications it's usually pretty bad for common types.

**Comment by dbaron** [comment]
I think it's also worth noting that this has a dependency on native file system here.

**Comment by annevk** [comment]
That's `defer` per #154 and per https://wicg.github.io/native-file-system/ looks pretty drafty still? In that case moving ahead with `defer` here too seems fine to me, but up to you.

**Comment by Jaifroid** [comment]
This API is launching in Chromium browsers as of Chromium 98. Just in case that should be a trigger for considering it further now.

**Comment by rayfoss** [comment]
Support for it is being actively worked on in vscode.dev, excalidraw launched support for it during the Chrome 92 origin trial.
