### ISSUE TITLE
Origin Policy

### ISSUE THREAD

**Issue by digitarald** [mozilla/standards-positions#160]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Origin Policy
* Specification or proposal URL: https://wicg.github.io/origin-policy/

### Other information

This came as feedback from sites on potentially having significant impact on mobile with slow connections. Specifically, the `unsafe-cors-preflight-with-credentials` aspects which cut the CORS preflight requests on restful calls, where API servers are on separate sub domains.

**Comment by past** [comment]
I'm guessing @martinthomson and @ckerschb will have opinions on this.

**Comment by dbaron** [comment]
also @annevk

**Comment by annevk** [comment]
In general this would be a great thing to have as it would deduplicate security policies and provide for optimization opportunities as OP points out. An origin being able to declare it's CORS-aware rather than having to do that for each individual response is a big win.

The biggest problem is the version negotiation scheme as discussed in some detail and motivated at https://github.com/WICG/origin-policy/issues/23. Origins want to proactively push this resource so the user agent has it early, but they only want to push it when it's changed relative to what the user agent already has. This makes it stateful and problematic in the same ways as cookies.

**Comment by comp615** [comment]
Wanted to throw a +1 on this. Origin-policy, specifically the ability to eliminate authed preflight requests on GET api calls, would be a huge boost to our network performance at Twitter, it would effectively halve our latency on all API requests in a very straight-forward (from our end) way, which would be a big benefit to the end user.

**Comment by dbaron** [comment]
Does `worth prototyping` seem like an appropriate position for this?

Are there any ways it's harmful?

Does anyone want to argue it should be `important` instead?

**Comment by annevk** [comment]
I think that as long as we use the top-level origin as additional cache key (as is the plan for our HTTP cache in general) and clear this together with cache and storage, it's not harmful. And that is the current standardization direction.

It'd be great if @ehsan could double check that though.

**Comment by ehsan** [comment]
> I think that as long as we use the top-level origin as additional cache key (as is the plan for our HTTP cache in general) and clear this together with cache and storage, it's not harmful. And that is the current standardization direction.
> 
> It'd be great if @ehsan could double check that though.

I agree with @annevk, in the light of the [recent changes to the version negotiation model](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md) adopted by this spec, it is no longer adding a new cross-site tracking vector, and as such it is now `worth prototyping`.
