### ISSUE TITLE
Secondary Certificates and TLS Exported Authenticators

### ISSUE THREAD

**Issue by MikeBishop** [mozilla/standards-positions#175]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Secondary Certificates / Exported Authenticators
* Specification or proposal URL: https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs-04 / https://tools.ietf.org/html/draft-ietf-tls-exported-authenticator-09
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

Exported Authenticators are proofs of possession of a certificate generated by one party to a TLS connection which can be validated by the other party to the TLS connection.  Secondary Certificates defines an HTTP/2 extension (eventually extensible to HTTP/3) to transport these tokens over an existing HTTP/2 connection.  This enables:

- Servers to proffer multiple certificates on the same connection, expanding the pool of hostnames the client could coalesce onto a single connection similarly to using a cert with many SANs, but with greater flexibility
- Client certificate authentication without needing renegotiation (prohibited in HTTP/2) and bound to particular request(s)

There have been discussions around whether this would make various stolen/misissued certificate attacks easier to perform; the [Required Primary Domain](https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs-04#section-5) certificate extension added to the document is considered to mitigate these attacks sufficiently.

**Comment by dbaron** [comment]
cc @martinthomson @ekr

**Comment by martinthomson** [comment]
I think that it makes sense to consider this as a single unit and to concentrate on secondary certificates.

This specification was initially created to address a lack of spontaneous client authentication in HTTP/2. The current version includes the option for servers to offer additional proof of authentication for identities that do not appear in the handshake, using entirely different certificates.

The client authentication case is reasonable, but not particularly interesting. It's functional, but hardly inspired.  We've managed without the feature for a few years now.  It's quite possible that this is holding some sites back from HTTP/2 though, and fixing the problem might be worth doing on its own.

The server authentication creates new opportunities for coalescing requests for different origins onto a single connection, even going so far as to remove the need to make DNS requests for those origins. This is far more interesting and controversial.

If you hold the view that DNS is a critical part of the system of attributing authority to origins, then this might be something that causes some concern. The draft proposes a new mechanism (the required primary domain that Mike mentions) that aims to ensure that only servers that opt in to this treatment are exposed to that risk. My view is that this is an appropriate response, so I don't see this issue as holding us back.

In my view, any dependence on unauthenticated DNS is unfortunate and largely a consequence of the legacy of the web.  It is better to place trust in our server authentication system of cryptographic assertions and certification authorities. Far better than than relying on the fragile system of routing and name resolution, even if those selfsame CAs are forced to do that themselves as a consequence of that same legacy. Of course, Mike [disagrees with me here on this point](https://tools.ietf.org/html/draft-bishop-httpbis-origin-fed-up), so we will continue to have that conversation.

The critical feature here is that connections to servers can be made without the name of the server ever being sent anywhere other than that server.  That could be a huge privacy win.  It could also represent a real problem for people doing name-based filtering and other such things, even if we might [strongly prefer approaches that rely on endpoint involvement](https://blog.apnic.net/2019/06/11/moving-control-to-the-endpoints-motivations-challenges-and-the-path-forward/).

The ability to split certificates more finely could also improve operations for big CDNs or hosts with lots of potential names at their servers.  For me, that is almost a demotivating justification, because it provides incentives for consolidation.  However, it is minor enough that it only bears mention; I don't think that it changes the outcome here.

In the end, with the caveats and unknowns here, I don't think that we can definitively say that this is important, but I do believe that it is `worth prototyping`.

**Comment by mnot** [comment]
A note of caution here: we have a rich history of over-designed features for performance (priorities, push) that engineers get enthusiastic about, but either don't get implemented, or don't get used. This feature (like them) adds a LOT of complexity, for very selective gains IF it's used effectively (which we won't know until it gets deployed, if it gets deployed).

Not to say it shouldn't be done, just trying to inject some realism.

**Comment by MikeBishop** [comment]
@mnot, there's a lot of truth to that.  The flip side is that we already have experience with greater coalescing and we know it helps.  (Provided the client is on a good network for HTTP/2; HTTP/3 will hopefully extend the benefits of coalescing regardless of network quality.)

The uncertain "art" here is for a massive provider like a CDN choosing *which* additional certificates to send.  However, sending certificates for origins you know are referenced from the content the client is requesting is nearly guaranteed to save a connection setup.  This, I think, is the clear win.
