### ISSUE TITLE
Open UI

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#177]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Open UI
* Specification or proposal URL: https://github.com/WICG/open-ui
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @smaug---- 

### Other information
See also: 
https://discourse.wicg.io/t/standardize-form-controls-components/3646

Proposal to standardize a new set of elements: 

* `<dropdown>` (modern replacement for select)
* `<file>` (modern replacement for input type="file")
* `<std-switch>` (proposal from Google is [here](https://github.com/tkent-google/std-switch))

Not exhaustive list... 

Cc'ing @gregwhitworth, in case there are further questions or we need clarification.

**Comment by marcoscaceres** [comment]
Bit more context from the [Discourse thread](https://discourse.wicg.io/t/standardize-form-controls-components/3646) - please go there for the links:

> These types of browser inconsistencies wouldn’t be such a huge deal if the form parts were agreed upon and reachable by web developers. Unfortunately, the majority of form controls and components aren’t which leaves web developers to go to great lengths to work around this; here’s simply one example blog post 21 detailing ways to work around the form control. This hack can be seen on many major sites such as Facebook and Twitter.

**Comment by dbaron** [comment]
I'm skeptical about completely forking the controls.  It seems like if there's parts of the existing stuff that don't get along with component-based stylability, we would probably be better off with something like an `appearance`-based toggle (e.g., between native / stylable / just a block/inline), but not with forking the entirety of the controls.

**Comment by gregwhitworth** [comment]
> I'm skeptical about completely forking the controls

I think it may help by defining to what depth forking is occurring and I am not really ready to discuss that since I need to dig into these areas further, and it may vary control to control.

Following the creation of the discourse thread, I wrote a blog post that digs into this further (https://www.gwhitworth.com/blog/2019/07/form-controls-components/) - I'll hopefully begin investigating `<select>` sooner rather than later. As we make progress about how to improve the story for the built in controls and components, styling being one aspect of that - we can discuss on each proposal how best to take them and whether a fork, and to what extent is necessary.

**Comment by annevk** [comment]
I would suggest defer on this and reviewing the outcomes of this effort on an individual basis rather than take a position on the whole thing.

**Comment by martinthomson** [comment]
Given that this is an effort that covers a lot of different proposals, we're going to close this without action.

We're positive on a lot of the work coming out of this group, but we will assess each item on its own merits. We already have a few open (and closed) issues from Open UI and we'd be happy to see more of those as work matures.
