### ISSUE TITLE
"Trusted JS" use-case for secure web conferencing

### ISSUE THREAD

**Issue by jan-ivar** [mozilla/standards-positions#205]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebRTC Next Version Use Cases
* Specification or proposal URL: https://github.com/w3c/webrtc-nv-use-cases/pull/49/files
* Mozillians who can provide input (optional): @ekr @martinthomson @stpeter @nils-ohlmeier 

### Other information

The PR contains two use-cases: “_trusted_ JS” vs. "_untrusted_ JS" for secure web conferencing.

The _"untrusted"_ use-case received consensus to merge at TPAC 2019, and seems compatible with Mozilla’s earlier efforts in this space with the webrtc-identity spec which Firefox implements, yet lacks support from other vendors.

However, the _“trusted”_ use-case is what this issue is about. Where do we stand on including it?

FWIW Google signaled interest in the trusted use case at TPAC. They have not signaled interest in the untrusted use case.

**Comment by dbaron** [comment]
I asked @martinthomson his position, and he agreed that we don't want this.

My initial reaction without reading the document was "Trusted JS" meant something entirely different from what it actually means.  That said, it doesn't seem particularly useful.  If we want trusted UI in the browser indicating who can see the video, it doesn't seem like giving the JS access to the video is an option.

I'm not super-clear on whether it's `harmful` or `non-harmful`, but I guess I'm inclined towards `harmful` simply because it appears likely to add a lot of extra complexity for little benefit.
