### ISSUE TITLE
QID Emoji

### ISSUE THREAD

**Issue by hsivonen** [mozilla/standards-positions#233]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: UTS # 51 Addendum: Unicode QID Emoji
* Specification or proposal URL: https://www.unicode.org/review/pri408/pri408-tr51-QID.html (linked from https://www.unicode.org/review/pri408/ )
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jfkthame, @makotokato, @zbraniecki, @vyv03354, @Manishearth

### Other information

The proposal is a mechanism to mint emoji via Wikidata semantics in a way that bypasses the normal emoji approval process. This kind of Wikidata-identified emoji would be encoded as multicodepoint sequences introducing multi-ASCII-codepoint (surrounded by non-ASCII delimiters) syntax for one grapheme cluster within "plain" text.

Deadline for responding to the Public Review Issue: 2020-04-20.

**Comment by hsivonen** [comment]
I suggest we find this proposal "harmful" and send feedback in response to the Public Review Issue to that effect.

Some reasons why I this proposal is harmful:

For interoperability, it's not enough to identify a concept, such as the examples given: "flag of NATO", "gelatin dessert", or "Triceratops". It's also necessary to establish a representative glyph and, more importantly, to have coordination between implementors about what concepts get glyphs in concrete implementations.

The present emoji process is useful for ensuring that there is mutual understanding of what glyphs to extend emoji fonts with in what time frame. (That is, each new version of Unicode mints a number of emoji that vendors have capacity to implement before the next version of Unicode.) Just focusing on abstract semantics and not concrete implementation gives me a flashback of the days when the Semantic Web focus was on _expressing_ stuff and not on what would concretely happen in _recipient_ software.

The proposal suggests that popular QID emoji would get normal code point assignments later. From experience with the Web, we know that legacy data doesn't go away, so this would end up with two ways to encode the same thing. (Also, while not directly a concern for Mozilla's field of Web browsers, emoji are typically used in private messaging, so finding out emoji popularity is potentially a problem in terms of the confidentiality of such messaging.)

It seems potentially problematic from the implementation perspective (even if the glyph availability coordination problem was solved) that the sequences of code point that would map to a single glyph are relatively long. Also, while ASCII code points do participate in ligatures and can serve as base characters for combining characters, I have a vague worry that having this many ASCII code points "ligate" may harm some optimizations in implementation (no concrete example).

**Comment by jfkthame** [comment]
I'm inclined to agree. I think a mechanism to identify arbitrary concepts from an open-ended external source that are then expected to behave as atomic "characters" is not something that belongs in a text encoding standard.

The existing approval process provides at least some hope of interoperability for the emoji that get encoded, and a valuable gatekeeping function to filter requests. This mechanism, if adopted, will throw that out of the window. Implementors will be constantly having to play catch-up with the fickle winds of popularity, trying to judge which QID sequences are important enough to require a font update this month.

**Comment by adamroach** [comment]
As an administrative issue, I've added this spec to the main index file, and will take on shepherding it.

**Comment by Manishearth** [comment]
> It seems potentially problematic from the implementation perspective (even if the glyph availability coordination problem was solved) 

This isn't the case, the QID emoji system uses the existing tag system that's already used for e.g. the Scottish flag emoji (🏴󠁧󠁢󠁳󠁣󠁴󠁿). We'd need to implement that as well anyway.

--------

> I'm inclined to agree. I think a mechanism to identify arbitrary concepts from an open-ended external source that are then expected to behave as atomic "characters" is not something that belongs in a text encoding standard.

> Just focusing on abstract semantics and not concrete implementation gives me a flashback of the days when the Semantic Web focus was on expressing stuff and not on what would concretely happen in recipient software.

> For interoperability, it's not enough to identify a concept, such as the examples given: "flag of NATO", "gelatin dessert", or "Triceratops".

I was in some of the UTC meetings discussing this proposal, and I think the intent of the proposal is different from what's captured in these comments.

The idea is not to let vendors mint emoji willy nilly based off of QID. Vendors also want interoperable emoji, for the most part. The idea is to cut UTC out of this process, with the hope that there will be a different, cleaner process that takes its place. The QID provides the bare minimum interoperability and is convenient: if Apple and Google both want a NATO flag emoji, the _encoding_ of this flag doesn't need to be figured out by allocating and agreeing upon code points, they both just need to decide to do it together.

This is similar to how flag emoji work today, Unicode is out of the business of determining what countries and subdivisions deserve emoji; it's up to vendors to decide that they all want a Californian flag. Unicode has laid the groundwork to make it so that if vendors want a Californian flag there's already a way to encode it in a tag sequence, but it doesn't make any kind of judgement on the flag being something you should support. They may eventually RGI it (like the Scottish flag).

**Comment by hsivonen** [comment]
If the UTC wants to delegate to Apple and Google, it seems that making the Unicode Consortium act as a registry that hands out a code point on "just the next available number" basis from an emoji block once Apple and Google have agreed to mint a new emoji should be the simplest part of the process. It seems wrong to push technical complexity onto the implementors to deal with such organizational issues.

I understand that it's advantageous to the Unicode Consortium not to assign a single number to any particular flag but to just say that users combined code points that have no intrinsic political meaning. And the result is an interop problem: Just consider how they render on Windows.

It seems bad to design as if all emoji required technical measures to put that kind of distance between the meaning and the UTC acknowledging the meaning considering that Unicode has been able to assign code points to the emblem of the Soviet Union as well as ideographic (incl. emoji) characters that can be considered profane as single characters (staying away from specific examples) without having to combine them with other characters to emerge offensive meaning. On the flip side, the QID emoji proposal doesn't solve issues like the gun emoji situation.

**Comment by hsivonen** [comment]
(FWIW: In the comment above where the text suggest that I should see the Scottish flag, I see a black flag in Firefox on Ubuntu. "Let's have more of this" doesn't seem great for interop.)

**Comment by Manishearth** [comment]
I don't see what that has to do with anything, you have this problem with basically every new emoji. The Scottish flag emoji is quite new.

**Comment by Manishearth** [comment]
> If the UTC wants to delegate to Apple and Google, it seems that making the Unicode Consortium act as a registry that hands out a code point on "just the next available number" basis from an emoji block once Apple and Google have agreed to mint a new emoji should be the simplest part of the process. It seems wrong to push technical complexity onto the implementors to deal with such organizational issues.

That's fair, but also, again, this technical complexity is already in stable unicode for subdivision flag emoji.

**Comment by dbaron** [comment]
One major benefit of emoji has actually been that it's made English-speaking developers care much more about correct Unicode support, since there are English-speakers who want to use Emoji, including Emoji that are outside of the Basic Multilingual Plane (BMP, plane 0).  The fact that new revisions of Unicode contain new emoji likewise provides pressure to keep Unicode support up-to-date, which is also valuable for having good support for other things added in that version of Unicode.  So I think there's some value to the multilingual nature of the Web of having an Emoji process where new Emoji that people care about get added in each new version of Unicode.

Also, the mechanisms for flag emoji probably needed to be the way they were to avoid Unicode having to wade into deeply political problems of deciding what was a country, what subdivisions of a country should be recognized, etc... political problems that do not exist at the same level for at least most other types of emoji.  So just because something was necessary to do flag emoji in a reasonable way doesn't mean that it's necessarily a good thing or should be extended to areas with less political difficulty.

**Comment by hsivonen** [comment]
Indeed, that flags are technically complex because they are politically complex is not a persuasive reason to make emoji in general as complex.

(In my earlier comment about ASCII optimizations, I misunderstood which code points the proposal was using for the digits that were displayed as ASCII digits. The proposal actually uses the same "tag" block for digits as subdivision flags use for letters.)

**Comment by hsivonen** [comment]
> I don't see what that has to do with anything, you have this problem with basically every new emoji. The Scottish flag emoji is quite new.

My point was that fallback to a black flag is a larger risk of miscommunication than a hex box. The QID emoji would than, I suppose, fall back to looking like SQUARED ID which maybe has fewer connotations than a black flag, but still isn't an obvious missing glyph marker.

**Comment by adamroach** [comment]
> I don't see what that has to do with anything, you have this problem with basically every new emoji. The Scottish flag emoji is quite new.

I think it's more complex than that. I'm using Firefox on Mac, and while I get a black flag in your comment above, if I copy and paste that glyph into the URL bar, it renders as a Scottish flag. This tells me that the _technique_ itself is (apparently) unimplemented in certain contexts, rather than the emoji glyph being unavailable. The handling of sub-national flags is not the poster child for this kind of feature that you might believe it is. 🙂

It's kind of a minor detail in the overall scheme, but I agree with Henri that the fallback characteristics of this proposal are really user-hostile. Perhaps if Unicode issued a new codepoint for this purpose (instead of 🆔) and associated it with a "broken emoji" glyph (akin to ![noimage](https://user-images.githubusercontent.com/2974852/71298331-35c86180-234d-11ea-94af-1754bdedba20.png)), the whole approach would be more palatable.

**Comment by Manishearth** [comment]
> My point was that fallback to a black flag is a larger risk of miscommunication than a hex box. The QID emoji would than, I suppose, fall back to looking like SQUARED ID which maybe has fewer connotations than a black flag, but still isn't an obvious missing glyph marker.

Ah, I see. The fallbacks were discussed internally (indeed, people were debating if you should be allowed to put arbitrary emoji fallbacks there so that e.g. a "dachsund" emoji is a QID sequence containing "dog" so its falls back to a dog).  It seems like people settled on the ID emoji, but I don't think that's something they're strongly tied to. We should definitely include a strong preference for a new fallbackable code point for this, I think that feedback would be taken well.


> The handling of sub-national flags is not the poster child for this kind of feature that you might believe it is. slightly_smiling_face

I'm not touting it as a poster child here! I was just saying that as far as implementation complexity goes, Unicode _already_ requires tag sequence support, so this doesn't add to existing complexity.

The scheme itself may have problems, of course.


> political problems that do not exist at the same level for at least most other types of emoji

They do :) Things like logos (the Apple logo PUA comes to mind) can't go in Unicode, but by this scheme fonts would at least have a common sequence to use if they wanted to support the logo.

Of course, it's debatable whether we _want_ fonts to have more power to go down this route.

--------

FWIW I don't necessarily disagree with anything here, I'm just trying to represent this proposal as well as I can since I was present for some of the discussions. I occasionally attend UTC meetings and would be happy to properly represent our position on this if we wanted. We're not voting members, but we don't have to be to be listened to. We should also submit a comment on the PRI if we want to.

**Comment by adamroach** [comment]
Re-pinging @makotokato, @zbraniecki, @vyv03354 for input.

**Comment by zbraniecki** [comment]
I don't have an experience with the QID that would make me able to form an opinion.

I only can point to @dbaron  comment on the value of using emoji's as a leverage to continue supporting Unicode in the English-dominant software.

**Comment by makotokato** [comment]
My concern is that this code point area is defined by out of Unicode Consortium.  Who management is normalization table for NFKC etc?  Actually, although we use ICU by IBM/unicode.org, ICU have to create normalization table for it. So I guess that It means that ICU/unicode.org have to manages all QID emoji too.

> Q: How are QIDs different than PUA characters?
> A: They are similar in that an organization / company can use them without requiring any action by Unicode. They are different in that the semantics are much narrower, and the behavior (as emoji) specified, so that implementations know how to process them (such as in linebreak). 

First emoji implementation by Japan mobile carrier (NTT docomo, KDDI and J-Phone/Softback) use different code point (most uses PUA), so it causes a lot of interoperability problem by email and web site. So it was nightmare. To resolve emoji nightmare for gmail, Google suggests emoji to unicode. If anyone can add/delete new emoji without strict process, it may become nightmare again.

**Comment by Manishearth** [comment]
These are not new code points, these are new sequences. And that's why
there's the QID system behind them, while vendors may disagree on which
sequences to implement, if they implement a sequence they already will
agree on what it means.

There is no normalization for these.

**Comment by hsivonen** [comment]
> while vendors may disagree on which sequences to implement

That seems like an interoperability problem. If developing browsers has taught us anything, it's that resolving technical disagreements by making things optional / vendor-dependent in specs is not a good way forward.

Leaving it to emoji font vendors to research content out there, a substantial proportion of which in the case of emoji flows in confidential person-to-person messages, in order to figure out what set of glyphs they need to supply in order to create a competitive emoji font raises the barrier of entry compared to being able to look up a code chart at unicode.org. That seems harmful.

> if they implement a sequence they already will agree on what it means.

It's already the case with normal emoji that glyph variation is too great for users to correctly interpret the meaning that's specced somewhere, so just having an abstract definition of meaning exist somewhere is no good if it doesn't result in glyphs that users interpret as that meaning.

For example, the name for U+1F3BF is SKI AND SKI BOOT and the reference glyph depicts a downhill ski boot and a ski in a downhill angle. Yet, Google doesn't depict the downhill ski boot but depicts skis and ski sticks that could plausibly indicate cross-country skiing, so the user-interpreted meaning of the [Google and Apple glyphs](https://emojipedia.org/ski-and-ski-boot/) are substantially different activities, so texting the emoji to someone across Android and iOS has a strong potential of miscommunication.

My conclusion from this is that having some repository of abstract meaning isn't enough, and instead there is a need to specify _more explicit constraints_ on glyph design to avoid cases like these. (In this case, the name says SKI BOOT and Google _still_ omitted the downhill ski boot.) If the current situation of having reference glyphs and names that says things isn't specific enough, it seems to me that the QID system would make things even worse.

> There is no normalization for these.

The proposal says "If an emoji QID sequence becomes popular, Unicode may define a different RGI representation using a character or sequence to save memory." Once that happens, one would expect the duality either to find its way into the K normalizations or to result in a new flavor of normalization.

Notably, for accessibility, it seems that a transition towards RGI is desirable. The proposal says: "For screen readers, it is anticipated that the normal behavior for an unknown QID tag sequence would be just to indicate that it is emoji. This is more information than would be provided for a PUA character, for example. For QID sequences that become popular, vendors could choose to provide more specific readings. Once a QID sequence is designated RGI, then Unicode would provide a short text-to-speech name (with localized versions available from CLDR) as it does for other RGI emoji."

It seems bad to put implementors and users through such a transition compared to the Unicode Consortium handing out actual code points to Apple and Google if the envisioned use case is to delegate emoji minting to Apple and Google.

> Things like logos (the Apple logo PUA comes to mind) can't go in Unicode, but by this scheme fonts would at least have a common sequence to use if they wanted to support the logo.

So the problem being solved would be to have a PUA-like mapping that degrades into squared ID rather than getting whatever glyph some font has mapped to U+F8FF? At this point, U+F8FF is so established that anyone making fonts who assigns a glyph to U+F8FF probably knows what they are doing. It seems bad to design for the Apple logo: Of all possible PUA code points, it should be the one that's least likely to _unintentionally_ get a miscommunicating glyph. (Presumably a QID sequence won't magically change whatever proprietary issues encumber the Apple logo.)

What should happen to the ConScript registry, which is probably the next-most-established allocation of PUA semantics after the Apple logo at U+F8FF? Should every character in Klingon and Tengwar get a QID sequence? Even if they shouldn't, is there a reason why believe that's not where the road would lead?

**Comment by adamroach** [comment]
> Should every character in Klingon and Tengwar get a QID sequence? Even if they shouldn't, is there a reason why believe that's not where the road would lead?

That's a really good point, and one that hadn't occurred to me yet. Once an escape hatch is added, the normal Unicode approval process runs the risk of become pretty much irrelevant.

**Comment by adamroach** [comment]
The general direction here seems hard to judge one way or another, although I do see a lot of concern about the effects of introducing such a feature. I'm tagging @linuxwolf and @stpeter for input, as they both have some Unicode experience, and might be able to provide insight to move things in one direction or another.

**Comment by Manishearth** [comment]
To be clear, I don't agree with the proposal, though I don't 100% disagree with it either. I was present when some of it was discussed so I wanted to make sure it was accurately represented, is all.

Given that it seems like we're leaning pretty strongly towards "nope".

**Comment by hsivonen** [comment]
> Given that it seems like we're leaning pretty strongly towards "nope".

Since there appears to be consensus towards "nope", and a useful expression of "nope" requires a write-up to be sent as a response to the Public Review Issue, I've started a [GDoc](https://docs.google.com/document/d/1BLU5-RW32IFI1Oth-EdhsUhPxvC7yRQwn1VkAEwLBeU/edit?usp=sharing) for drafting a write-up (mostly edited copypaste from comment upthread here).

**Comment by adamroach** [comment]
I'm hearing here an emerging consensus for marking this "harmful." I'll wait for Henri to finish his document, and then summarize it into a position for the dashboard.

**Comment by hsivonen** [comment]
There haven't been any comments on the GDoc. As far as writing style goes, it's not exactly my best literary output, but how about we wrap this up and submit?

How should the representativeness of the document be indicated? Should it have just my by-line with Mozilla affiliation indicated? Should "we urge" be replaced with "Mozilla urges"?

**Comment by jfkthame** [comment]
Thanks for writing this up, Henri. "Mozilla urges" is good, IMO.
It should be clear this is not just an individual opinion but an organizational position.

**Comment by hsivonen** [comment]
Thanks for the in-doc comments.

> "Mozilla urges" is good, IMO.

I've made this change. Would 'Mozilla Feedback on PRI #408 “QID Emoji”' be an appropriate title? (The title is required to contain the PRI number and title.)

The deadline is April 20. How do we arrive at the decision that this is OK to send as Mozilla-level feedback?

**Comment by adamroach** [comment]
For the purposes of the dashboard, I propose closing this with a disposition of "harmful" and the following explanation:

> Mozilla has a number of concerns about this proposal, including: (a) the lack of reference glyphs is likely to increase miscommunication between users; (b) having a formal, versioned approval process provides synchronization between implementors for adding new glyphs, and this proposal removes that; (c) QID glyphs that are later adopted into Unicode would result in duplicate encodings, perhaps in perpetuity; (d) gathering telemetry about the popularity of specific emoji for the purposes of more formal codepoint assignments may cause privacy issues and provides incumbent implementors a competitive advantage; and (e) there are no barriers to abuse of the QID system to create non-emoji characters as a general end-run around the Unicode process.

**Comment by hsivonen** [comment]
The feedback document is now in the Unicode Document Registry: http://www.unicode.org/L2/L2020/20110-qid-emoji.pdf
