### ISSUE TITLE
Consider adding a `mixed` status

### ISSUE THREAD

**Issue by tantek** [mozilla/standards-positions#249]
In some evaluations, we determine that a standard or feature may have some merit, or be mostly good, but discover that it does have some harmful aspects. Since we think the problem being solved is user-relevant, and perhaps may even agree with the approach, we avoid marking these as "harmful", and end-up averaging down to "worth prototyping" (i.e. with actual concerning caveats, beyond just clarification or bugs that need fixing), or "non-harmful".

For example, I would have advocated (and I believe we would have stated) in https://github.com/mozilla/standards-positions/issues/194#issuecomment-568581041 that that spec is "mixed" rather than just "non-harmful".

Per [@bholley](https://github.com/bholley)’s comment in [242](https://github.com/mozilla/standards-positions/issues/242#issuecomment-574395499), ironically, averaging "worth prototyping" (or "non-harmful") and "harmful" down to "non-harmful" seems itself potentially harmful due to the risk of the position being misconstrued as being more positive than our evaluation actually states in prose.

Proposal: add "mixed" with a description like:

Our evaluation of this specification is **mixed** , meaning while we may otherwise consider the majority of this work neutral (non-harmful) or positive (worth prototyping, important), we have identified specific actually harmful aspects (beyond just bugs or underspecified aspects that need clarification), that require resolution before we can place a neutral or positive summary status on it. If there are many harmful aspects that seem endemic to the design or approach despite a specification’s good intentions / use-cases, then "harmful" should be used as the status. "mixed" does not mean just any mix of statuses, but rather specifically a mix of "harmful" and another status.

(Originally published at: https://tantek.com/2020/014/b1/consider-adding-mixed-status)

**Comment by martinthomson** [comment]
After discussion on #242 and privately, we've decided not to do this.

Primarily, sending mixed signals is not useful to others.  In some important ways, the point of this exercise is to create a clear signal to other browsers and other web users.

Each position we take is explained, either as a comment on the issue or in details on the dashboard.  We will use that text to explain issues we see.  Though that text might be ignored, we have no evidence that this happens too often. On the contrary, people do rely on our explanations.

For this to work, we might need to be more willing to take a negative position when serious issues exist and then update that position as the issue is resolved.
