### ISSUE TITLE
Multiple Storage Buckets : Durability in buckets and specific APIs.

### ISSUE THREAD

**Issue by asutherland** [mozilla/standards-positions#254]
There was a lot of discussion at TPAC 2019 about Multiple Storage Buckets.  https://github.com/whatwg/storage/issues/2 serves as a spec root for this, and at TPAC 2019 a small group came up with a broad strokes [presentation](https://docs.google.com/presentation/d/143w70xtfqculs5x-bPgTOwu6GZO6uTOYeBjnN63pzs8/view) on the subject matter.

A motivating aspect of the discussion was Chrome/Blink's [intent to prototype (formerly implement)](https://groups.google.com/a/chromium.org/d/msg/blink-dev/aDDJXM8TZnk/xdhSlY-ZDwAJ) a relaxed durability transaction.  The consensus of those attending the WebApps WG who expressed interest in storage and IndexedDB seemed to be that it was reasonable for buckets to support a durability/performance knob and that it was also reasonable to allow this to also be expressed at a transaction level with the same semantics.

@annevk and myself were the Mozillians most directly involved in the process.

Chrome/Blink has indicated a desire to move forward with shipping https://github.com/w3c/IndexedDB/issues/50 and would like to know Mozilla's public stance on this.  Since this would constitute the first step in exposing such semantics as part of the standards process, I figured it was worth filing an explicit standards-position bug on this.

Spec-wise, I guess I'd view this as marking Multiple Storage Buckets as `worth prototyping` and treating IDB transaction durability as related to that.

**Comment by annevk** [comment]
High-level summary of the idea: The web platform has many storage APIs to address various different/overlapping use cases. The idea behind buckets is that rather than having on large storage bucket (i.e., area) for an entire origin this is divided up. When you use a storage API you'd indicate the bucket (or you'd go from the bucket to the respective API, undecided). That helps with storage management of multiple applications on a single origin, but also allows for adding additional metadata that the browser can use in conjunction with "frecency" to free up storage space.

**Comment by annevk** [comment]
Given that this is mostly an idea at this point without a concrete form I think we should close this issue until it's further along. (Generally there's at least an explainer before we establish a position on something.)

And as far as the IDB issue goes I think it's fine to say Mozilla supports that change?

Does that seem okay @asutherland?

**Comment by asutherland** [comment]
Yes, that makes sense.  I'm currently planning to work on an explainer for buckets in 2020H1 and I'll file a new issue for that when the time is right.

**Comment by annevk** [comment]
Seems this is #475 now.
