### ISSUE TITLE
Event Timing

### ISSUE THREAD

**Issue by npm1** [mozilla/standards-positions#283]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Event Timing
* Specification or proposal URL: https://github.com/WICG/event-timing
* Mozillians who can provide input (optional): @mstange attended some of the presentations to the WebPerf WG and seemed to agree on the usefulness of the API. @bdekoz is currently attending WebPerf WG meetings so he may have thoughts.

### Other information

First Input Timing (event timing restricted to the first input event) already ships in Chrome. Chrome would like to ship full Event Timing sometime in the near future.

**Comment by dbaron** [comment]
w3ctag/design-reviews#324 also has some feedback on this spec.

**Comment by dbaron** [comment]
My personal reaction is that providing measurements on event processing times is a worthwhile problem to be solving.  The major concerns I can think of are:
* how well this addresses the use case of detecting event processing delay, and
* whether there are any security issues.

As to the first one, I think it's clear this is a metric that could be gamed by a hostile developer who's told to improve this metric but doesn't actually care about improving user-perceived performance, by deferring the work of handling the event until after the next paint.  I don't think that is, in itself, a problem.  However, people might have *other* reasons to defer work such that it ends up being after the next paint, and this might both (a) lead to the metric not measuring what was expected or (b) lead to things like "oh, we have to revert that change because it made our numbers on event timing much worse" when what really happened is that it started measuring the real work that happened.  I'm curious if we have any way to know how common that sort of deferral of work is.

That said, I would lean towards saying this is `worth prototyping` but I'd like to get input from others before marking it as such.

**Comment by npm1** [comment]
Your concern is totally valid and it is indeed common to have the event handling work be asynchronous. This API only captures the synchronous work, and we do have plans to enable a developer to annotate their work and capture the async work (but that may happen via the User Timing API). Note that even if the work is synchronous, a developer can still get some benefits from the API by looking at the input delay (hardware timestamp to when input begins being processed). This part cannot be gamed easily and must be fast in order to provide a good interactivity experience (it's necessary, though of course not sufficient). A developer should look at high (80-99) percentiles of input delay and make sure that they are low. Then the developer can focus on making actual processing time fast, via this API if they know work is synchronous or in conjunction with User Timing if it's not.

**Comment by npm1** [comment]
Update: we intend to augment this API with interactionID.

Explainer: https://gist.github.com/npm1/9c2b95ece116d9bcb4bc224155e23777
Spec PR: https://github.com/WICG/event-timing/pull/102

I figured I'd just update this issue instead of creating a new one given that this one has not been closed yet.
