### ISSUE TITLE
Scheme-bound cookies

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#298]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Scheme-bound cookies
* Specification or proposal URL: https://github.com/mikewest/scheming-cookies
* Mozillians who can provide input (optional): @annevk @martinthomson @ddragana

### Other information

This came up in w3ctag/design-reviews#483, but it seems like it might be worth discussing a Mozilla position on this sooner rather than later.

**Comment by annevk** [comment]
Reducing the scope of cookies along this axis seems like a major win. The slightly weird aspect is the `Sec-Nonsecure-Cookie` header, but it seems that would only ever be temporarily deployed.

cc @bakulf

**Comment by hsivonen** [comment]
This indeed seems like a major win and, other than `Sec-Nonsecure-Cookie`, I suggest rating this `important`.

As for `Sec-Nonsecure-Cookie`, I think it's not harmful as the time-limited transition mechanism, but I'm very skeptical about it having an audience. For you to have an audience, you need developers who haven't yet gotten their act together and who are also willing to write and deploy code rather than having users log in again (or similar). Is there actually an audience of substantial size like that? Anyway, since it looks non-harmful if time-limited, the main reason to argue against it would be implementation cost of our side. I will let others comment on that.

**Comment by dbaron** [comment]
Given the value of separating secure and non-secure storage, I'd be happy to rate this as `important`, although I'd also be happy to go with `worth prototyping` if others felt that was appropriate.  Curious on @annevk's opinion on that.
