### ISSUE TITLE
RFP: Proposal for a z-layer property

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#34]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Proposal for a z-layer property
* Specification or proposal URL: https://discourse.wicg.io/t/proposal-for-a-z-layer-property/2364

### Other information
Proposal to group z-layer properties into groups as a means of solving the `z-index: 9999999999` hack everyone uses.

@dbaron - maybe you can suggest some Moz CSS folks to ping for opinions?

**Comment by dbaron** [comment]
So this seems relatively simple, but it's not clear to me how it solves anything.  Why wouldn't the ads just use the same thing to pop above everything?  And why isn't the existing capability of putting the ad in a stacking context (e.g., with `position: relative; z-index: 0`, or other ways) sufficient to stop things inside it from popping out?

I guess maybe `non-harmful` is appropriate here?

**Comment by annevk** [comment]
I suspect this is actually asking for "top layer" control as defined at https://fullscreen.spec.whatwg.org/#new-stacking-layer? In any event, once there's an actual proposal and not only a WICG forum thread we could consider this, but since it hasn't really moved to that stage I'm going to close this. Feel free to reopen if I missed something.
