### ISSUE TITLE
Media Feeds

### ISSUE THREAD

**Issue by beccahughes** [mozilla/standards-positions#370]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Media Feeds
* Specification or proposal URL: https://github.com/wicg/media-feeds
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by martinthomson** [comment]
**Summary: We don't think the Media Feeds API is useful. It amplifies a harmful user feature. It uses a harmful technology approach.**

The proposal for the Media Feeds API is proposing to turn an [existing Google data format](https://developers.google.com/actions/media/how-to/create-a-feed) into a format that is understood by browsers. Based on the [objectives](https://github.com/WICG/media-feeds/blob/master/explainer.md#objectives) stated in the explainer, the reason for doing this appears to be for some form of integration of YouTube recommendations into the Chrome [media controls](https://blog.google/products/chrome/manage-audio-and-video-in-chrome/), which currently allow control of audio or video that is playing in a background tab.

The Media Feeds API is **not useful because many of these capabilities are already provided to sites**. Web pages have a great deal of flexibility in how they manage the content they display, and many of these functions are already provided by sites. Most of the additional media-specific actions are provided by the [Media Session API](https://w3c.github.io/mediasession/). We would prefer that additions to the Media Session API be considered for those use cases that are not supported.

This is **harmful to users** because it appears to be **designed to amplify or promote YouTube's video recommendations feature, which has a significant history of promoting misinformation, conspiracies, and hateful content**. See [YouTube, the Great Radicalizer](https://www.nytimes.com/2018/03/10/opinion/sunday/youtube-politics-radical.html) (by Zeynep Tufekci), and also [the TheirTube project](https://twitter.com/mozilla/status/1284622480091549698) for a description of these problems. Our recent personal experience shows that they are still present.

We also note that there have been privacy concerns, another possible harm to users, related to how content is acquired outside of the context of a browser tab. Use of cookies or other storage in this context might cause problems for browser privacy features or tools that understand the privacy characteristics of websites. This problem, if present, is likely to be fixable.

This is a **harmful technology approach** because it uses **overly-complex Semantic Web technology into browsers (in an ambiguously-specified way)**. Both JSON-LD and schema.org have a history of mixed, if not poor, development. This could advance a years-long campaign to burden browsers with this technology. It is also a harmful technology approach because it **ignores existing communities that are building formats for the Web** and prior work that fits better with existing Web technologies.

**Comment by rektide** [comment]
first, i have no affiliations to disclose. nor much to recommend me. i am a mere web developer whose interested in expanding hypermedia in interesting ways.

> proposing to turn an existing Google data format into a format that is understood by browsers

this is not a Google data format. this is a https://schema.org/DataFeed object. the data-format is JSON-LD. it's using https://schema.org/DataFeed as vocabulary, and that doesn't, to me, equate to Google's thing either.

if you'd take the time to go to [https://schema.org/docs/about.html](https://schema.org/docs/about.html), you'd see that yes, seven of the people are Google. but Yahoo and Yandex and Microsoft are also present. most activity that I see occurs through the w3c hosted community groups.

>  it uses overly-complex Semantic Web technology (in an ambiguously-specified way). Both JSON-LD and schema.org have a history of mixed, if not poor, development.

this makes me want to cry. this seems like opinion & bias, and it seems like a cruel opinion & bias that stomps out the effort of those who want a richer hypermedium to work with. rdfa & microdata & json-ld are hardly new, are incredibly interesting systems. right now they are problematic in that they are mainly used by big entities for large tasks, but the idea here, to me, has always been that has a page has many "things" on it and those things should be able to talk about themselves in rich & empowering ways that users & their user-agents should be able to leverage to improve their experience.

i for one see nothing at all that has anywhere near the potential to enrich & empower users on the web & i wholeheartedly believe it is our best future.

this curt dismissal of those hopes is very dismaying. i would hope for at least a more neutral stance.

> Most of the additional media-specific actions are provided by the Media Session API

this claim does not make any sense to me. the Media Session is about you the user's media session. if I am a podcasting site, I would include the users playlist of added podcasts.

but as a podcasting site, i think it's reasonable that there are standards that i can use to enumerate, to site-map out, the podcast content that i have. the Media Feed proposal would let countless user-agents & extensions generate neat & interesting ways of previewing, of showing this content. there's so much potential here to let the web radiate the neat things it has. i don't see how this proposal overlaps with Media Sessions.

> This is harmful to users because it appears to be designed to amplify or promote YouTube's video recommendations feature

maybe that is a part. but again, if i have my own podcast site, it would help amplify & promote my videos too, help give users a central experience to see all the new media that is occuring.

i would not want to force my users to have this experience, but i would be very interested both as a content-provider and as a user to have a cross-site means of looking at my Media Feeds.

> We also note that there have been privacy concerns, another possible harm to users, related to how content is acquired outside of the context of a browser tab. Use of cookies or other storage in this context might cause problems for browser privacy features or tools that understand the privacy characteristics of websites. 

this point seems vague ("have been  privacy concerns") and i would like to see some actual contentions put down rather than aspersions cast. but i too would like certainty that this enhancement does not amplify a user's footprint online or otherwise put them at risk.

----

with apologies, i'm very disappointed because it feels like there's a real failure to begin to imagine the upside here. i would far prefer sites be able to publish useful meta-data about what they have, than the current situation, which is that they cannot. the highest fidelity of media feed information we have online is podcasts, which are an extremely lo-fi stream that barely gets the filename across & which relies on something that was never specified in the first place and numerous unoffficial extensions on top of that to try to deliver enough information to present new podcasts in a timely manner that users might be able to understand. might.

based off podcasting we've seen countless interesting podcasting applications arise.

this is an obvious & straightforward growth of the unrefined & crude podcast base, using vocabulary from a reasonably respected ontology provider. apologies, but the idea that sites presenting more information about themselves would constitute such a matter of Harm seems shocking to me. the web is indeed a much less optimistic & sunny place than it was a decade ago, but sites saying what they have being written up as a bad & harmful threat, because some sites have bad & harmful content, is the core message i get from this reply (knife in linked-data's back aside), & that attitude feels like we're giving in to a slippery slope view of the web.

yours, with hope & i hope respect too, rektide

**Comment by andreicristianpetcu** [comment]
Happy to see Mozilla once again stand up for users!

**Comment by jonaskuske** [comment]
@rektide I like your podcasting example. But please mind one of the stated non-goals of this proposal:

>  Media feeds are currently limited to video content. Audio-only content such as music or podcast are out of scope for now.

Maybe if "empowering small, individual media sites" was more of a priority for this, Mozilla's (and my) opinion would be different? Because right now I have to agree with Mozilla: this looks primarily like a way to promote the YouTube feed to become part of the browser UI.

**Comment by beccahughes** [comment]
Thanks for the response.

The Media Session API is not appropriate here since it is for in-band media metadata while the page is open and the Media Feeds API is designed to provide out-of-band media recommendations while the page is closed, kind of similar to RSS feeds work today.

I would like to ask if you could clarify the “overly complex” and “ambiguously specified” claims since the spec goes into detail about what types and properties are supported as well as how a browser can easily parse them. We also only use a very small amount of JSON-LD to make the feeds compatible with the JSON-LD and don’t require browsers to implement the full JSON-LD spec. 

I would also like clarification on which web community is being ignored?

Finally, none of this API is YouTube specific and will work with any video site.

**Comment by dbaron** [comment]
> The Media Session API is not appropriate here since it is for in-band media metadata while the page is open and the Media Feeds API is designed to provide out-of-band media recommendations while the page is closed, kind of similar to RSS feeds work today.

It would be interesting to see this explained in [the explainer](https://github.com/WICG/media-feeds/blob/master/explainer.md) whose Objectives section currently references the [media controls](https://blog.google/products/chrome/manage-audio-and-video-in-chrome/), which seems to be largely about media playing within active Chrome tabs (though often background tabs rather than foreground).

> I would like to ask if you could clarify the “overly complex” and “ambiguously specified” claims since the spec goes into detail about what types and properties are supported as well as how a browser can easily parse them. We also only use a very small amount of JSON-LD to make the feeds compatible with the JSON-LD and don’t require browsers to implement the full JSON-LD spec.

The underlying issue about use of JSON-LD being ambiguously specified is the one I described in https://github.com/w3ctag/design-principles/issues/128#issue-446681228 which I think is a failure of the JSON-LD spec itself to clearly define the two processing models that the proponents of the spec talk about when they advocate for it.  Defining behavior with reference to the JSON spec rather than the JSON-LD spec (which it looks like the media feeds spec is pretty close to doing) does remove the ambiguity.  And I'd note the "overly complex" was a reference to Semantic Web technology, not to Media Feeds.

> I would also like clarification on which web community is being ignored?

The two communities I'm aware of that are most closely related to this work are [JSONFeed](https://www.jsonfeed.org/) (which has already developed a JSON-based feed format) and [MediaRSS](https://www.rssboard.org/media-rss).  There are also other feed formats like Atom and RSS.  Others may know more.

> Finally, none of this API is YouTube specific and will work with any video site.

Sure, but YouTube still looks like the major use case.

**Comment by beccahughes** [comment]
> It would be interesting to see this explained in [the explainer](https://github.com/WICG/media-feeds/blob/master/explainer.md) whose Objectives section currently references the [media controls](https://blog.google/products/chrome/manage-audio-and-video-in-chrome/), which seems to be largely about media playing within active Chrome tabs (though often background tabs rather than foreground).

I have updated the explainer to explain this more clearly and I have added a use case which covers the user journey.

> The underlying issue about use of JSON-LD being ambiguously specified is the one I described in [w3ctag/design-principles#128 (comment)](https://github.com/w3ctag/design-principles/issues/128#issue-446681228) which I think is a failure of the JSON-LD spec itself to clearly define the two processing models that the proponents of the spec talk about when they advocate for it. Defining behavior with reference to the JSON spec rather than the JSON-LD spec (which it looks like the media feeds spec is pretty close to doing) does remove the ambiguity. And I'd note the "overly complex" was a reference to Semantic Web technology, not to Media Feeds.

This has been done, we have removed all references to JSON-LD in favour of JSON.

> The two communities I'm aware of that are most closely related to this work are [JSONFeed](https://www.jsonfeed.org/) (which has already developed a JSON-based feed format) and [MediaRSS](https://www.rssboard.org/media-rss). There are also other feed formats like Atom and RSS. Others may know more.

I have added an "alternatives considered" section to the explainer detailing why these two standards are not appropriate for this use case and I have also invited the communities to comment.

**Comment by SneakyWhoami** [comment]
I exist as a web user, a designer, a developer and as a developer on browsers (and other user agents) in general.The Media Feeds API is stupid. The HTML5 Living Standard is stupid. It's amazing how close we were to an internet which was a smooth repository of all human knowledge, and which has now become a cesspool of stupid 20MB single page applications. All to make it heavier so that we will gladly jump on AMP.

No thanks.
