### ISSUE TITLE
CSS Media Queries Level 5

### ISSUE THREAD

**Issue by tantek** [mozilla/standards-positions#389]
## Request for Mozilla Position on an Emerging Web Specification

  * Specification Title: Media Queries Level 5
  * Specification or proposal URL: https://drafts.csswg.org/mediaqueries-5/
  * Caniuse.com URL (optional):
  * Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1434491
  * Mozillians who can provide input (optional): @heycam, @dbaron
  * W3C Tag Design Review issue: none

### Other information

We have implemented several of the features in Media Queries Level 5: [prefers-reduced-motion](https://bugzilla.mozilla.org/show_bug.cgi?id=1434491), [prefers-color-scheme](https://bugzilla.mozilla.org/show_bug.cgi?id=1494034), and most recently, [prefers-contrast](https://bugzilla.mozilla.org/show_bug.cgi?id=1506364) (as [announced Monday](https://wiki.mozilla.org/Firefox/Roadmap/Updates#2020-07-06)).

In general Media Queries Level 5 has several accessibility enhancing features and thus we should consider an overall status of "important".

Label: w3c.

(Originally published at: https://tantek.com/2020/191/b2/)

**Comment by dbaron** [comment]
I think it may be preferable to add entries for particular features in this specification (or maybe groups of features, if there are clear groups) than for the specification as a whole.

I say that both because I think the granularity of our standards-positions should probably match the granularity at which we would choose to (or not to) implement features, and because I think it's possible the scope of mediaqueries-5 may change over time (either due to additional new features being added or to features being moved between levels).

**Comment by dbaron** [comment]
Closing in favor of taking a position on #393 instead.
