### ISSUE TITLE
Relative indexing method on JS indexables (.at)

### ISSUE THREAD

**Issue by syg** [mozilla/standards-positions#458]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Relative indexing method
* Specification or proposal URL: https://github.com/tc39/proposal-relative-indexing-method
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @codehag 

### Other information

Firefox shipped a previous iteration of this proposal named .item, which was then found to be web incompatible. Thank you for doing the work! Confirming position for the current rename to `.at` and possible future renames.

**Comment by annevk** [comment]
Do we really need another way to get to a code unit of a string?

**Comment by codehag** [comment]
@annevk some context regarding accessing the code unit of a string -- this proposal would have been blocked without this by a few members of the committee. We raised our concerns about it here: https://github.com/tc39/proposal-relative-indexing-method/issues/20

When this was raised again in the last meeting, I checked with the team if the inclusion of this method on strings, specifically for code units, was a blocking issue. We decided that, while it would have been nice to see this as its own proposal, such a suggestion would block the progress of the entire proposal.

Regarding motivation over all, one initial goal here was to use the name `index`, would have been a great way to unify methods across the dom and js. That won't be possible due to the web compatibility issue uncovered by @evilpie. However, the overall problem that this solves is worthwhile. Relative indexing is very useful for typed arrays and arrays and will be a quality of life improvement for developers. I am a bit hesitant regarding the naming as I am afraid we might run into another web compatibility issue.

I am open to hearing other arguments on this! It was primarily discussed within the spidermonkey team.

**Comment by codehag** [comment]
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1658308

**Comment by codehag** [comment]
So.... any objections to "worth prototyping"?

**Comment by annevk** [comment]
(To be clear, no objections from me. Just slightly sad to see 16-bit code units further enshrined, but they are already so it doesn't matter much.)

**Comment by codehag** [comment]
This fell off my radar, I will make a pr today.
