### ISSUE TITLE
RegExp match indices

### ISSUE THREAD

**Issue by syg** [mozilla/standards-positions#478]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: RegExp match indices
* Specification or proposal URL: https://tc39.es/proposal-regexp-match-indices/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1519483
* Mozillians who can provide input (optional): @codehag 

### Other information

At the January 2021 TC39, we got consensus for the /d flag. V8 would like to ship soon with the /d flag, as the proposal has been stage 3 for more than a year.

**Comment by codehag** [comment]
The proposal initially advanced to stage 3 and is worth prototyping (from my perspective anyway). 

It provides additional information about the start and end indices of captured substrings relative to the start of the input string. While RegExp provide the index of the captured group, it is not enough information for advanced use-cases. This proposal provides the start and end of a given match. 

The recent change is due to performance issues with the initial design, this was discussed by the SpiderMonkey team. We are in favor of the change to use the `/d` flag, and had expected some of the performance issues highlighted by V8 and JSC. There shouldn't be any major issues in implementing this. cc @iainireland

**Comment by annevk** [comment]
@codehag since this is rather small and nobody had any other input I guess we should just close this?

**Comment by codehag** [comment]
Sure
