### ISSUE TITLE
Custom Highlight API

### ISSUE THREAD

**Issue by sanketj** [mozilla/standards-positions#482]
**Request for Mozilla Position on an Emerging Web Specification**

Specification Title: Custom Highlight API
Specification or proposal URL: https://www.w3.org/TR/css-highlight-api-1/

Feature summary:
The Custom Highlight API extends the concept of highlight pseudo-elements by providing a way for web developers to style the text of arbitrary ranges, rather than being limited to the user agent defined ::selection, ::inactive-selection, ::spelling-error, and ::grammar-error. This is useful in a variety of scenarios, including editing frameworks that wish to implement their own selection, find-on-page over virtualized documents, multiple selection to represent online collaboration, or spellchecking frameworks.

With the lack of this functionality in the browser today, web developers and framework authors are forced to modify the underlying structure of the DOM tree in order to achieve the rendering they desire. This can quickly become complicated in cases where the desired highlight spans elements across multiple subtrees, and also requires DOM updates in order to adjust highlights as they change. The custom highlight API provides a programmatic way of adding and removing highlights that does not affect the underlying DOM structure, but instead applies styles to text based on range objects.

**Comment by annevk** [comment]
cc @smaug---- @emilio

**Comment by smaug----** [comment]
I think the StaticRange handling _inside_ the API is a a mistake. That forces one to do possibly slow validation when painting or it leads to just weird behavior if there has been DOM mutations.

But in high level, Highlight API is quite close to what Gecko's Selection API does already - support multiple selections which all support multiple ranges.

**Comment by sanketj** [comment]
Thanks @smaug----! Does Firefox have any plans to start implementing the highlight API?

Regarding your point about using live range internally for highlights, I'll respond to that in this issue: https://github.com/w3c/csswg-drafts/issues/4597

**Comment by dandclark** [comment]
An update - Chrome and Edge are likely going to ship Custom Highlight API soon: https://groups.google.com/a/chromium.org/g/blink-dev/c/pxgVrAzMfyk

Since the last activity on this thread there was a lot of discussion about the use of StaticRanges, mainly in https://github.com/w3c/csswg-drafts/issues/4597. The end result was that CSSWG resolved to go ahead with internal StaticRange use given research showing performance benefits vs live Ranges.

The most notable change to the Chrome implementation since then is probably the switch to the highlight pseudo inheritance model as laid out in https://drafts.csswg.org/css-pseudo-4/#highlight-cascade.

Any updates on Mozilla's position on this API would be appreciated. Thanks!

**Comment by emilio** [comment]
I think generally we're positive. I think a few of the aspects of the CSS inheritance / currentColor are rather over-complicated tho.

**Comment by martinthomson** [comment]
Let's go with positive here; if anyone thinks we need a dashboard entry, say so (preferably by opening a pull request).
