### ISSUE TITLE
New html attribute indicating searchability in hidden content

### ISSUE THREAD

**Issue by vmpstr** [mozilla/standards-positions#483]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: An HTML attribute to enable searchability in hidden content
* Specification or proposal URL: https://github.com/w3c/csswg-drafts/issues/5595#issuecomment-776914538

### Other information

There has been some discussion about this on CSSWG when the proposal was for a new CSS property. Since then, we have moved to an HTML attribute, but a lot of the discussion in the [proposal URL's root issue](https://github.com/w3c/csswg-drafts/issues/5595) still applies.

**Comment by emilio** [comment]
cc @annevk @smaug----

**Comment by annevk** [comment]
That's a lot of context to wade through for something that hasn't even made it to whatwg/html yet. It seems like a reasonable idea though. Perhaps we should make `<details>` "work" first?

**Comment by chrishtr** [comment]
> That's a lot of context to wade through for something that hasn't even made it to whatwg/html yet.

See also [this issue](https://github.com/whatwg/html/issues/6040) in whatwg/html, filed a while back.

> It seems like a reasonable idea though.

I'm going to interpret that as "implementer interest", especially since @emilio and @tantek also made positive comments.

> Perhaps we should make `<details>` "work" first?

Automatically opening `<details>` is part of the plan, in addition to the new attribute and event.
`<details>` is tracked [here](https://github.com/whatwg/html/issues/4051).

**Comment by annevk** [comment]
It seems there's now a more concrete proposal at https://github.com/whatwg/html/issues/6040#issuecomment-785991421.

**Comment by annevk** [comment]
Let's duplicate this into #612.
