### ISSUE TITLE
Implement service worker modules

### ISSUE THREAD

**Issue by ghazale-hosseinabadi** [mozilla/standards-positions#499]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Allow workers to execute module scripts too.

* Proposed spec: https://w3c.github.io/ServiceWorker (see "type" in the section)

* Specification or proposal URL: https://docs.google.com/document/d/1SeQ085YdBTtW3D_ygSpO0Wz2DAe8QiS1gj37IG5lstg/edit#

**Comment by annevk** [comment]
This is worth prototyping. We'll probably not update the dashboard for this as it's somewhat minor and unless there are other comments I would expect to close this as such next week.

**Comment by abflow** [comment]
I think that before we should implement the ability for the service worker to run any number of arbitrary complex scripts, we should think about a security model protecting the users of the application.

Because, imagine that deep down within the dependencies of a service worker module, we have a hidden backdoor that is programmed to run after the service worker completed the installation of the application. The backdoor may be programmed to run one hour after the installation, or two days or even three weeks after the installation, silently waiting for the users to bring their own private documents in places that are now accessible to the application and thus to the spyware/malware that could be deployed from the backdoor.

We have to think of ways able to mitigate this scenario.

**Comment by annevk** [comment]
@abflow I don't see how that's related. Service worker modules don't change the security properties of service workers. I'm closing this as per earlier comment.

Thanks for asking @ghazale-hosseinabadi!

**Comment by abflow** [comment]
> Service worker modules don't change the security properties of service workers.

What security properties ?

**Comment by asutherland** [comment]
> What security properties ?

- https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
- https://w3c.github.io/ServiceWorker/#security-considerations

**Comment by abflow** [comment]
"_Potentially Trustworthy_" is not really what can be called "secure"...

https://html.spec.whatwg.org/multipage/webappapis.html#secure-context

**Comment by mangelozzi** [comment]
> I think that before we should implement the ability for the service worker to run any number of arbitrary complex scripts, we should think about a security model protecting the users of the application.
> 
> Because, imagine that deep down within the dependencies of a service worker module, we have a hidden backdoor that is programmed to run after the service worker completed the installation of the application. The backdoor may be programmed to run one hour after the installation, or two days or even three weeks after the installation, silently waiting for the users to bring their own private documents in places that are now accessible to the application and thus to the spyware/malware that could be deployed from the backdoor.
> 
> We have to think on ways able to mitigate this scenario.

Could not the same argument be used against any module imports? The concept of libraries is fundamental to programming.

Many people require to use a library to in their service worker to use IndexedDB because the API is so confusing. Now everyone must inline their code to use the modules. How is that more secure? If you have a dependency, you are going to add it one way or another.

**Comment by AlbertMarashi** [comment]
Bump... Need service workers to be able to support `import` statements - critical for service worker development using **SvelteKit**.

Currently chrome supports this, so it would be nice to see it in Firefox
