### ISSUE TITLE
Request for position: COEP: credentialless

### ISSUE THREAD

**Issue by ArthurSonzogni** [mozilla/standards-positions#539]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Cross-Origin-Embedder-Policy: credentialless
* Specification or proposal URL: https://github.com/WICG/proposals/issues/31
* Caniuse.com URL (optional):
* Bugzilla URL (optional):
* Mozillians who can provide input (optional): @annevk (?)

### Other information

- [explainer](https://github.com/mikewest/credentiallessness/blob/main/explainer.md)
- [specification](https://htmlpreview.github.io/?https://github.com/mikewest/credentiallessness/blob/main/index.html)
- w3ctag: https://github.com/w3ctag/design-reviews/issues/582
- Basic test website: http://coep-credentialless.glitch.me/

**Comment by annevk** [comment]
As stated in https://github.com/w3ctag/design-reviews/issues/582#issuecomment-768122624, in order for this to not increase the attack surface, browsers need an implementation of [Private Network Access](https://wicg.github.io/private-network-access/) and [ORB](https://github.com/annevk/orb). Both are still in progress and somewhat experimental.

Then, given the way nested documents are dealt with, there's also an implicit dependency on [Anonymous iframes](https://github.com/camillelamy/explainers/blob/master/anonymous_iframes.md).

I think the security properties work out, but it's a significant amount of added complexity.

Is there interest in this beyond Google Earth?

**Comment by annevk** [comment]
Thanks @ArthurSonzogni! It definitely helps to see the interest in this beyond Google and I tend to agree that making this the default could be attractive.

I have a hard time seeing how Private Network Access and ORB are not dependencies, given that this gives access to cross-origin isolation. Even with those this still increases the attack surface, but I think everyone is more-or-less okay with giving up on defending the remaining IP-authenticated resources.

With those sorted, I would say COEP: credentialless is worth prototyping. I think the same goes for Anonymous iframes.

I have a much harder time with COOP: same-origin-allow-popups-plus-coep as from a privacy perspective (and arguably also from a security perspective) popups (in particular browsing contexts with an opener) are deeply problematic and I'm not convinced they are worthy of further investment. Further entrenching them seems incompatible with our longer term goals.

**Comment by ArthurSonzogni** [comment]
> I have a hard time seeing how Private Network Access and ORB are not dependencies, given that this gives access to cross-origin isolation.

Private Network Access is a dependency. However, today, SharedArrayBuffer [is still available](https://developer.chrome.com/origintrials/#/view_trial/303992974847508481) on Desktop without COOP/COEP. It will be as long as existing websites using them have no possibility to migrate to cross-origin isolation. So today, you can already leak **subresources** requested from the private network. Adding `COEP:credentialless` on Chrome doesn't make the current state worse, and it will accelerate the removal of SAB. Without Private Network Request, `COEP:credentialless` won't have achieved the final vision, I agree. We want both, but `COEP:credentialless` can be experimented in parallel on Chrome even if Private Network Request hasn't launched yet. Private Network Request is critical and I have no doubt it will manage to launch.

About ORB, I am no more sure to understand why the resources that will be blocked by ORB will represent an additional risk inside a crossOriginIsolated context with COEP:credentialless. The problem can't be about leaking the data since it was requested without credentials. Could you please explain the risk you were thinking about? I agree this is an important project, but I am no more sure this is a dependency.

**Comment by annevk** [comment]
The resources that are vulnerable to Spectre with a credentialless mode are those on networks that the Browser can reach but the Attacker Server cannot. Private Network Access reduces the set of resources, but not completely due to the nature of the internet and the various setups people have created over the years. ORB further reduces the set of resources attackers can get hold of.

**Comment by ArthurSonzogni** [comment]
Hi @annevk,
At the moment, we are evaluating shipping it in Chrome M96 based on the feedback we've got so far. 
Please let me know, if you think we should reconsider this.

**Comment by annevk** [comment]
It would help to get Google's perspective on what I wrote in my previous comment. As I understand it neither PNA nor ORB is done, so shipping this first seems dangerous.

**Comment by ArthurSonzogni** [comment]
Yes, in the long run, PNA is required to protect those vulnerable resources. However, today, they are already vulnerable in Chrome without `COEP:credentialless`.That's because we still maintain the [reverse OriginTrial](https://developer.chrome.com/origintrials/#/view_trial/303992974847508481) for SharedArrayBuffer. We have to [extend](https://groups.google.com/a/chromium.org/g/blink-dev/c/RlhJTtFVN-I/m/nJwpvuSIBQAJ?utm_medium=email&utm_source=footer) it as long as most large websites have difficulties deploying cross-origin isolation. `COEP:credentialless` is helping to migrate some of them.

I think you can see @MikeWest message [here](https://www.google.com/url?q=https://github.com/w3ctag/design-reviews/issues/582%23issuecomment-768116322&sa=D&source=editors&ust=1631025503881000&usg=AOvVaw0wg0H51UsMnjkYbjHsmyE3):

> I think it's a hole we can temporarily accept in Chromium, as it's strictly better than our status quo, and will allow us to keep SharedArrayBuffer deprecation on track by unblocking a few sites we've talked to that are having issues with COEP: require-corp and dependencies.
> ~@MikeWest

So we think it's security-positive in Chrome given the OT, and helps getting rid of it.
Also, we're actively working on launching PNA. See [deprecation trial.](https://developer.chrome.com/blog/private-network-access-update/)

----

About ORB, I think I would give the same argument.
Moreover, Chrome has [CORB](https://chromestatus.com/features/5629709824032768). Yes ORB is better, but we are not in a terrible position given CORB.

**Comment by annevk** [comment]
I thought a reverse OT was limited to a select number of "trusted" parties. `credentialless` isn't that. I might be missing something though.

As far as shipping this goes it seems dangerous to me without PNA/ORB.

As far as implementer interest goes I think our position should be worth prototyping, modulo PNA/ORB.

This probably doesn't warrant a dashboard entry, but I'll leave this open for a bit in case anyone feels otherwise.

**Comment by ArthurSonzogni** [comment]
About PNA. We just [discussed](https://groups.google.com/a/chromium.org/g/blink-dev/c/Zr9n9_LG7s4/m/Vx-D4PZoBAAJ) shipping it earlier on the `COEP:credentialless`, `COEP:X` or `COI `subset of websites. As long as the OT remains, this wouldn't improve the status-co , however it may allow PNA to be a little more aggressive with its schedule.

---

As far as I know. The security implications of an Origin Trial are the same as a full launch. That's because everybody can freely sign a token against Chrome's private key on: [https://developer.chrome.com/origintrials/](https://developer.chrome.com/origintrials/#/view_trial/303992974847508481) and immediately start using the feature. That's the case for the SAB one.

What can be done is disabling remotely an OriginTrial or some individual trial token (due to abuse, or because developers did not respond to the survey).
Code is [here](https://source.chromium.org/chromium/chromium/src/+/main:components/embedder_support/origin_trials/origin_trial_policy_impl.h;l=41;drc=a9641800e0e8f7a2ea9a5f55f831b632e990a0e0;bpv=1;bpt=1).

A reverse OT is a normal OT. 
I don't know any OT where creating new token was restricted to a particular party. That would feel wrong to me, because this would give some website some kind of temporary advantages over others. It's a little less important for a deprecation, but still. Maybe you know some examples where it happened, but I don't myself.

**Comment by domenic** [comment]
(This is getting more into Chromium policy territory and maybe should be on blink-dev instead, but...)

Although restricting signups is not part of OT infrastructure, there are some potentially-relevant differences here. Notably, if we use OT instead of fully shipping, _we have a list of all the origins that are breaking COI protections by using credentialless without PNA/CORB_, and we can do targeted outreach to them in the future, e.g. to make sure implementing PNA or CORB won't break them.

Additionally, there is [a cap on OT usage](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#19-are-there-any-usage-limits-on-experimental-features) which ensures this unsafe configuration would not go above 0.5% of page views, which might be relevant since we're eventually trying to drive it down to 0% of page views.

**Comment by SamVerschueren** [comment]
> Is there interest in this beyond Google Earth?

Hi everyone 👋 ! Not sure if this is the right place to put this, but we at [StackBlitz](https://stackblitz.com) are building a product where people can play around with all kinds of front-end frameworks. Not only that, recently we released [WebContainers](https://blog.stackblitz.com/posts/introducing-webcontainers/), a technology which allows you to run Node.js locally inside your browser.

WebContainers heavily rely on SharedArrayBuffer and Atomics and thus has to implement cross-origin isolation. At the moment, we use Chrome's origin trial to make it work, but we would love to have support for other browsers like Firefox (and hopefully Safari at some day) as well. Cross browser support is much requested by our community.

For that, StackBlitz would also benefit from `credentialless` mode because when testing `require-corp`, we noticed that it breaks a lot of the user-generated content. The only solution we could come up with is by running all external requests through our own proxy. But that is definitely not something we want to do in terms of privacy.

**Comment by annevk** [comment]
Given that nobody challenged this should be worth prototyping without dashboard entry, I'll consider this closed.

**Comment by bholley** [comment]
Just a heads-up to folks following this thread that Firefox 104 (which ships today) supports credentialless as an [origin trial](https://wiki.mozilla.org/Origin_Trials). We encourage site operators to deploy it and get in touch with any feedback.

**Comment by Yery** [comment]
This change broke chess analysis in the lichess , please see https://lichess.org/forum/lichess-feedback/nnue--firefox-10402
