### ISSUE TITLE
Scalable Video Coding (SVC) Extension for WebRTC

### ISSUE THREAD

**Issue by jesup** [mozilla/standards-positions#544]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Scalable Video Coding (SVC) Extension for WebRTC
* Specification or proposal URL: [https://www.w3.org/TR/webrtc-svc/](https://www.w3.org/TR/webrtc-svc/)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): [https://bugzilla.mozilla.org/show_bug.cgi?id=1571470](https://bugzilla.mozilla.org/show_bug.cgi?id=1571470)
* Mozillians who can provide input (optional): jesup, jib, bwc, mt

### Other information
Bernard Aboba of Microsoft has been the major push behind this I believe, and is the current editor.
SVC has a lot of patents associated with it, I believe, and many holders aren't members of W3. H264-SVC was (if I recall) spearheaded by Vidyo, and at least one of their H264 SVC patents is part of MPEG-LA.
A less-capable way to provide similar capabilities is available via WebRTC simulcast.

**Comment by jesup** [comment]
I'm quite concerned with the patent issues surrounding SVC (and even more so H264-SVC).   Chrome has an [intent to experiment](https://groups.google.com/a/chromium.org/g/blink-dev/c/--ZpYlTo6LE/m/h0RzUIWkAAAJ) from 2019

**Comment by alvestrand** [comment]
How to do SVC is a property of the codec. If you believe that a certain codec is license-OK, and that codec implements SVC, I don't think there should be any additional patent related concern with controlling that SVC functionality via this interface.

I see no reason to assume that a browser has to implement all modes for all codecs in order to be compliant with the specification (indeed, some codecs are incapable of some of the modes listed).

Of course practicing any flavor of H.264 without a license has known issues.

**Comment by aboba** [comment]
[AV1](https://aomediacodec.github.io/av1-spec/av1-spec.pdf) was developed within [AoMedia](https://aomedia.org/), which has paid considerable attention to  codec IPR concerns.

Within AV1, SVC support is mandatory both for encoders and decoders.

A sampling of the AoMedia membership is listed [here](https://aomedia.org/membership/members/)

Note that the membership includes Google, Vidyo, Polycom, Cisco, Facebook, Intel, Microsoft, arm, NetFlix, Amazon, Apple, Mozilla, Samsung, Tencent, HuaWei, etc. 

The AV1 license is [here](http://aomedia.org/license/).
The specification for the AV1 RTP payload is [here](https://aomediacodec.github.io/av1-rtp-spec/). 

If there are concerns about AV1 licensing or codec IPR, AoMedia is well positioned to respond.

Support for AV1 encoding in Chromium WebRTC is tracked [here](https://bugs.chromium.org/p/chromium/issues/detail?id=986069).
The latest PR is [here](https://chromium.googlesource.com/chromium/src/+/66fcc92cdfb9c63528cf54416b99ae59c0eb97dd).

**Comment by murillo128** [comment]
In fact, this would work together with simulcast, as for example currently Chrome automatically adds temporal scalability (L1T2) for each simulcast layer. 

When chrome changed the number of temporal layers, it was quite a big issue for many SFU developers, so having an API to explicitly setting the number of temporal layers via API would be quite important in its own:
https://bugs.chromium.org/p/webrtc/issues/detail?id=11366&q=vp8%20temporal&can=2 https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/discuss-webrtc/N1sMEBJhOz4)

What would be overlapping is spatial scalability and simulcast, that is, using L2T2 with simulcast. But If i recall it correctly, that was not allowed.

Regarding H264, I am not sure if OpenH264 supports annex g for full SVC support, but that would require adding support for rfc6190 in libwebrtc which is not currently available. 

What you can do with OpenH264 is enable only temporal scalability (the L1T2 or L1T3) modes and still use rfc6184 (.i.e the normal h264 codec in sdp). It was supported at some moment in time in libwebrtc, but in order to be able to use it on any SFU, it required to use the framemarking header extensions too. AFAIK, the support for that in libwebrtc was abandoned, but could be added back in the future (together with the av1 dependency descriptor).

As a sfu developer, this API would be very important for us as we plan to migrate to AV1 SVC as soon as possible (we already support this API on our web broadcaster).

**Comment by aboba** [comment]
It is possible to configure spatial scalability along with simulcast. Not sure why that would be useful, but it is permitted. 

What is not possible is to configure "S" modes along with simulcast.  The application has to choose whether it will send simulcast streams each on a separate SSRC, or whether it will send them all on a single SSRC.  Doing both (e.g. some simulcast streams on a single SSRC, others on separate SSRCs) is prohibited. 

OpenH64 supports encoding of temporal scalability.  AFAICT WebRTC-capable browsers can decode temporally encoded H.264/AVC bitstreams. The problem is that RFC 6184 does not include a field for the TID, which makes life hard for the SFU. TID is supplied by the Framemarking RTP header extension, or alternatively, by the Dependency Descriptor RTP header extension.

**Comment by jesup** [comment]
@alvestrand Just because a codec has a copyright license that's ok doesn't mean that it doesn't fall afoul of patents.  There are plenty of implementations of H264 that have reasonable licenses, but you can't deploy/use them (or use certain features of them) without paying patent fees.  (Perhaps the word 'license' here is confusing.)

That said, I'm fairly certain that AV1 took considerable care that their SVC  specification was unlikely to impinge on any known patent claims, and I don't know of any that would impinge on an SVC control surface in WebRTC.   It's still unclear to me if *using* (or making usable) H264 SVC is possible without patent licenses, and I don't know any status on patent issues around SVC for VP8/9; however I don't think that needs to block adoption of the control surface in WebRTC, especially given the likelihood that it's usable in AV1.

The consensus (including myself and @martinthomson ) at Mozilla is that we're ok with moving forward with WebRTC SVC.   We would love to see more definitive documentation on the patent status of the codecs with regards to using SVC to provide guidance to implementors.

**Comment by murillo128** [comment]
FWIW openh264 supports temporal scalability without using annex g (SVC) and it was in use by libwebrtc (and in chrome) for a while together with the frame making header extension.

**Comment by Orphis** [comment]
This has stalled for over a year. Can we have an update from Mozilla over this issue? @jan-ivar

**Comment by jesup** [comment]
Mozilla is positive on this.   I'd love to see any known patent issues around SVC highlighted and documented, but we can move forward.
