### ISSUE TITLE
Request for Position on AccessHandles for the Origin Private File System

### ISSUE THREAD

**Issue by fivedots** [mozilla/standards-positions#562]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: AccessHandles for the Origin Private File System
* Specification or proposal URL: https://github.com/WICG/file-system-access/blob/main/AccessHandle.md
* Mozillians who can provide input: @annevk 

### Other information

We've requested a position on a previous iteration of this API: #481 . This new proposal is a response to feedback that Storage Foundation seemed to duplicate existing functionality and should be integrated into the File System Access API.

Thank you!

**Comment by annevk** [comment]
To set some context, we consider the File System Access API harmful (see #154, #545) because of the capabilities that involve granting direct access to the user's file system. That set of APIs also offers an Origin Private File System. We'd consider that Origin Private File System worth prototyping if it were to be split from the File System Access API.

Now this AccessHandle API in turn essentially provides a better way of manipulating files in a file system, though it's scoped to the Origin Private File System for the moment (see https://github.com/WICG/file-system-access/blob/main/AccessHandle.md#exposing-accesshandles-on-all-filesystems). I continue to think it looks good and I'll ask others to take a look as well.

A thing I'm wondering about is if we were to split Origin Private File System from File System Access API and Firefox/Safari were willing to adopt that as well as this AccessHandle API, what sense would it make for us to support the "current" File System Access API way of manipulating files. As far as I can tell that would just be legacy baggage at that point. (And would that reduction in points of access to file manipulation change anything about naming (maybe) or overall API shape (seems less likely)?

**Comment by domenic** [comment]
> As far as I can tell that would just be legacy baggage at that point.

My understanding (but the domain experts like @fivedots or @mkruisselbrink should confirm) is that the existing API has different tradeoffs vs. the access handle API in terms of persistance and durability. Something like, access handle does more stuff in memory so it can be faster, but then your data could get lost due to power failure? https://github.com/WICG/file-system-access/blob/main/AccessHandle.md#what-makes-the-new-surface-fast seems to hint at that.

Whether that should really lead to two separate APIs, or whether the old API could be recast in the style of the new one with different backing semantics, is not clear to me.

**Comment by fivedots** [comment]
Hey @annevk, I was wondering if this issue was ready to be closed, given the context of https://github.com/whatwg/sg/issues/176 and subsequent migration to https://github.com/whatwg/fs?

**Comment by annevk** [comment]
Thanks for the reminder @fivedots! I've created https://github.com/mozilla/standards-positions/pull/614 to establish a formal position for the File System standard. This addition to that standard can be considered worth prototyping. I don't think we need to add a separate entry for it in our dashboard, but if anyone disagrees, please speak up!

**Comment by jimmywarting** [comment]
> To set some context, we consider the File System Access API harmful (see https://github.com/mozilla/standards-positions/issues/154, https://github.com/mozilla/standards-positions/pull/545) because of the capabilities that involve granting direct access to the user's file system.

I also thinks it hurts 😢  
you are already allowed to do that today to some degree, could we at least ship some parts of the features that isn't harmful? a.k.a the things that are already possible to do without the new and shiny api? you are already allowed to read files and directories out of `<input type=file webkitdirectory>` and recrsivly walk a directory from DataTransferItem drag and drop.
So it would have been nice to have `DataTransferItem.prototype.getAsFileSystemHandle` but requesting write permission would not be allowed and would always throw an error when calling `handle.requestPermission(...)`
the handle would be read-only for just the session and not be persistent 

again the `showDirectoryPicker` & `showOpenFilePicker` isn't also directly so harmful. it's still pretty useful and you can already basically do those things today without the new File System Access. The thing that you see as potentially harmful is the write access and the persistent read access to the user's file system. I think you can at least ship some features out of the file system access. you can also save files with `<a download>` so i don't really see why we could also allow for showSaveFilePicker either... 

a good compromise would be to at least ship some part of the file system access but don't implement the `requestPermission` if that is what is deemed harmful.

**Comment by annevk** [comment]
We plan to support the WHATWG File System Standard. And yeah, I could imagine extensions to drag & drop and copy & paste along those lines, as well as `<input type=file>`. Baby steps.

Anyway, that's all out-of-scope for this issue and as nobody has spoken up since my statement on Feb 11, I'm closing this.

**Comment by baughmann** [comment]
I work for a very large organization that always errs on the side of caution. Yet, we do not ship Firefox on any of our systems, and its often because of decisions like this.

I would humbly advise Mozilla to take the lead in guiding the implementation standards like this in a manner that is safe and beneficial to consumers rather than just sit it out. The internet needs Mozilla and Firefox to stay relevant. It does not good to hand the reins to the likes of Google and Apple.
