### ISSUE TITLE
Request for position: prerendering

### ISSUE THREAD

**Issue by nyaxt** [mozilla/standards-positions#613]
## Request for Mozilla Position on an Emerging Web Specification

This is a request for Mozilla’s position on prerendering. Some browsers have long been shipping with the feature, and Chrome would like to also explore doing so, in an interoperable way.

We opened an issue at https://github.com/whatwg/html/issues/7533 , and have a draft spec at https://github.com/WICG/nav-speculation.

Mozillans who can comment

We’d appreciate your thoughts on this.

Thanks,
@nyaxt

* Specification Title: Prerendering, revamped
* Specification or proposal URL: https://github.com/WICG/nav-speculation
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @annevk and @smaug---- discussed this with @domenic previously

**Comment by domenic** [comment]
Hi Mozillans,

Chrome shipped same-origin prerendering in May. We're now looking to expand this to cover cross-origin same-site prerendering, i.e. cases like `https://a.example.com/` prerendering `https://b.example.com/`. This *will* include credentials/storage access, since those are site keyed, but it will also require an opt-in from the target site via a new HTTP response header, `Supports-Loading-Mode: credentialed-prerender`, to protect the origin security boundary.

We've updated the spec and explainer in https://github.com/WICG/nav-speculation/commit/16570ff808267383a393064ff951b764911be78f , with perhaps the most relevant reading being:

- A new [section of the prerendering explainer](https://github.com/WICG/nav-speculation/blob/main/prerendering-same-site.md#more-details-on-cross-origin-same-site) giving our full analysis of what this expansion does in terms of security and privacy properties.
- The overall [`Supports-Loading-Mode` explainer](https://github.com/WICG/nav-speculation/blob/main/opt-in.md) (which includes a few values we aren't yet shipping, such as `uncredentialed-prerender`).
- [The `Supports-Loading-Mode` spec](https://wicg.github.io/nav-speculation/prerendering.html#supports-loading-mode), as well as [where it is used in the main fetching part of the prerendering spec](https://wicg.github.io/nav-speculation/prerendering.html#navigate-fetch-patch).

Thanks for your time!

**Comment by sefeng211** [comment]
Just to add some details - Chrome supports `same-site prefetching`, `cross-site prefetching` and `same-site prerendering`.  

As far as I can tell, both web sites (lots of factors to consider here) and browser vendors can also benefit from this. [Slides for TPAC 2023](https://docs.google.com/presentation/d/1GK92nCORW5vKd7LgGtTsgy35eqTV7P71l05pHsni8ok/edit?usp=sharing) had some success stories about this.

**Comment by smaug----** [comment]
prerendering adds possibly quite a bit power usage overhead, both on server and client side.

**Comment by domenic** [comment]
Our metrics for Chrome show no significant differences in power usage in the control vs experiment groups, if it helps. (Well, battery usage, at least.)

**Comment by zcorpan** [comment]
I'll merge this with https://github.com/mozilla/standards-positions/issues/620 since we're reviewing them together.
