### ISSUE TITLE
Request for position: `font-palette` and `@font-palette-values`

### ISSUE THREAD

**Issue by drott** [mozilla/standards-positions#617]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Color font styling by means of the `font-palette` property 
* Specification or proposal URL: https://www.w3.org/TR/css-fonts-4/#propdef-font-palette
* Caniuse.com URL (optional): PR https://github.com/Fyrd/caniuse/issues/6137
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1461588
* Mozillians who can provide input (optional): @jfkthame 

### Other information

We're planning to ship this in Chrome soon, and we find this a useful companion feature to COLRv0 and COLRv1, extending versatility of color fonts usage. We'd be happy to see this supported in Firefox. Thanks for commenting on Mozilla's position.

**Comment by jfkthame** [comment]
Speaking for myself, I think this is a useful and uncontroversial addition, allowing authors greater flexibility and control when working with multi-colored fonts (such as emoji and other symbol sets, as well as decorative alphabets).

In principle it could be used to do some "underhanded" or misleading things, such as re-coloring a Regional-Indicator flag symbol to look as though it represents an entirely different country. But if someone controls the CSS of a page, so that they could do this, then they could equally well inject an entirely different font that has "wrong" glyphs, and achieve the same result. So I don't see any real concern here.

So I think we should classify this as "worth prototyping". @tantek @annevk Any additional thoughts?

**Comment by martinthomson** [comment]
Yes, those risks seem commensurate with other CSS features and the feature appears to contribute something useful. Closing as "worth prototyping".

**Comment by drott** [comment]
Thanks all for the quick and positive response to this position request.
