### ISSUE TITLE
@scope

### ISSUE THREAD

**Issue by andruud** [mozilla/standards-positions#625]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Cascading and Inheritance Level 6 (parts about `@scope`).
* Specification or proposal URL: https://drafts.csswg.org/css-cascade-6/#scope-atrule
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): @emilio 

### Other information

At this time I'm requesting a position for `@scope` only, not including:

- Scoped Descendant Combinator, e.g. `.a >> .b`.
- Selector Scoping Notation, e.g. `(.foo / .bar) .a { ... }`.

**Comment by emilio** [comment]
Over-all seems reasonable, though I'm a bit confused/concerned about the `:scope` rules. The spec says:

> [Selectors are scoped](https://drafts.csswg.org/selectors-4/#scoped-selector) to the given [scope](https://drafts.csswg.org/css-cascade-6/#scope), with the [:scope element](https://drafts.csswg.org/selectors-4/#scope-element) being the [scoping root](https://drafts.csswg.org/selectors-4/#scoping-root).

I think the `:scope` definition is circular there (because the scoping root is defined to be `:scope`), but ignoring that... I think that means that you need to compute the scope for a given selector before you start matching it, right? Which means you need to do a bunch of extra work for selectors that don't end up matching, which is a bit unfortunate... Of course you can do the bloom filter rejection earlier, presumably, but still..

**Comment by andruud** [comment]
Yeah, `:scope` is the most annoying part here.

> I think that means that you need to compute the scope for a given selector before you start matching it, right?

I was exploring the possibility of dynamically figuring out the scope element when `:scope` is encountered in the selector, so at least for e.g. `:scope > .foo` we'd check `.foo` first before doing horrible things to check for `:scope`. But that has some challenges as well ...

**Comment by zcorpan** [comment]
Closing as dup of #472
