### ISSUE TITLE
Request for position: Link type "modulepreload"

### ISSUE THREAD

**Issue by BenjaminAster** [mozilla/standards-positions#635]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Link type "modulepreload"
* Specification or proposal URL: https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload
* Caniuse.com URL (optional): https://caniuse.com/link-rel-modulepreload
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The modulepreload link type has long been part of the HTML specification. It provides a way for developers to preload JavaScript modules that will be imported via another JavaScript module.
```html
<link rel="modulepreload" href="./foo/main.js" />
```
Without modulepreload, the user agent must first download the primary JavaScript file before it can download its dependencies specified in an ES6 import. These imported JavaScript modules can import other modules as well, and so on. Because of this, the user agent has to make several network requests successively instead of making them all at once in parallel. This results in a noticeably slower page loading speed.

Blink is currently the only browser engine that supports this, which is a shame because preloading JavaScript modules is an essential thing that modern browsers are supposed to support. Would be great if this could be implemented in Gecko.

**Comment by martinthomson** [comment]
This is not an appropriate forum for asking about implementation plans for Gecko.  As the item is in the specification already, any position we take here is moot unless we are considering a proposal to remove the item from the spec.

If you have input, https://bugzilla.mozilla.org/show_bug.cgi?id=1425310 tracks the implementation of this item.  However, if your input is "please fix this", I refer you to the voting feature of Bugzilla rather than commenting.
