### ISSUE TITLE
CSS Overscroll Fixed Elements

### ISSUE THREAD

**Issue by bmathwig** [mozilla/standards-positions#643]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Overscroll
* Specification or proposal URL: https://drafts.csswg.org/css-overscroll/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
Regarding resolution of [[css-overscroll] Whether to move position:fixed elements during overscrolling](https://github.com/w3c/csswg-drafts/issues/6299):

* RESOLVED: fixed-position elements whose scroller is not their containing block do not participate in overscroll
* RESOLVED: the former statement also applies to sticky element when stuck

We like to get an official position on the resolution to add a note about behavior to the specification.

Chromium Intent to Ship:
https://groups.google.com/a/chromium.org/g/blink-dev/c/ldUEhY-C3OE

Mozilla Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1760368

**Comment by theres-waldo** [comment]
As an engineer working on the relevant code areas of Firefox, the resolution of this issue seems reasonable to me. We have recently implemented this for `position:fixed` in https://bugzilla.mozilla.org/show_bug.cgi?id=1760368, and have https://bugzilla.mozilla.org/show_bug.cgi?id=1772626 on file for `position:sticky`.

One edge case that came up during the implementation that doesn't work correctly in Firefox is interacting with content is that "revealed" by an overscroll effect causing it to e.g. slide out from under a fixed element. Not sure if this is worth filing a spec issue about (I _think_ the intent is clear that such areas _should_ be interactable?) but due to the increased implementation complexity we are treating this as an edge case with lower priority.

cc @dlrobertson

**Comment by dholbert** [comment]
We should mark this as "worth prototyping", given that we're clearly already prototyping it. :)
