### ISSUE TITLE
RFP: BigInt

### ISSUE THREAD

**Issue by littledan** [mozilla/standards-positions#65]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: BigInt
* Specification or proposal URL: http://tc39.github.io/proposal-bigint
* Caniuse.com URL (optional): None
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1366287

### Other information

BigInt provides a second numeric type in JavaScript: unlimited-size integers. In the Blink Intent to Ship thread for BigInt, @bzbarsky [noted](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/vIVL6eDQKf0/WEfVYnyRDQAJ) that, although @cxielarko has been developing a BigInt implementation for SpiderMonkey (as an employee of Igalia, as part of partnership Bloomberg), it has not yet been accepted by Mozilla engineers. It'd be great to have an official Mozilla position on whether BigInt should be added to the Web Platform.

cc @tschneidereit @syg @jorendorff @jswalden

**Comment by tschneidereit** [comment]
I think we should support this.

BigInt has good use cases in JavaScript and is an important piece of the JS/Wasm integration story. The proposal is very well-written and accompanied by changes to other affected specs for cases such as BigInt serialization in indexedDB and structured cloning.

There is broad consensus in TC39 about this spec, and at least three independent implementations are progressing rapidly: the SpiderMonkey implementation done by Igalia, a V8 implementation done by V8 team members (but with some reviews by Igalia people) and a JSC implementation largely done by an Apple intern. The implementations are largely or entirely independent: most of the code is necessarily different because it has to be tightly integrated into existing engines. Additionally, while V8 and JSC share an underlying BigInt math library - developed by the V8 team -, SpiderMonkey uses [gnump](https://gmplib.org/).

Note that I'm talking about the proposal in general, not necessarily about all of its details: I haven't reviewed the spec in detail, nor the WIP patches against SpiderMonkey.

**Comment by jorendorff** [comment]
>  it has not yet been accepted by Mozilla engineers.

This is blocked on my review. I don't foresee any major issues. It's a big monolithic patch to review and there's other stuff ahead of it in the queue.

**Comment by ekr** [comment]
Can someone who understands the TC39 proposal better than i do comment on whether the operations are intended to be constant time? It seems like a likely use of this will be for cryptography, but if the algorithms are not constant time, then this could lead to vulnerabilities

**Comment by jswalden** [comment]
I'm not a fan of BigInt.  I think it is a problem largely solvable by libraries, I think JS's adherence to there being One Number Type is worth continuing (maybe multiple types would have been better Back In The Day, but I think it's too late for it now), and I think the demand for this is sufficiently esoteric that making it a library thing is preferable.

But I also get the sense that most people think otherwise here, I am not strongly inclined to argue against it, and _even if_ I were so inclined I don't get the sense I would be successful and persuasive about it.  So I'm not actively going to stand against BigInt, nor argue much that we shouldn't support it.

**Comment by jswalden** [comment]
@ekr BigInt is arbitrary sized integers.  Ain't gonna be doing constant time algorithms on arbitrary sized integers.  I don't think BigInt has any real crypto implications.  At least not when the crypto being written is being written by conscientious engineers who know the limitations of their chosen tools.

And as far as crypto goes -- if we are going to actively attempt to enable and offer good support for having user-defined crypto operations, I think this is worlds better addressed in Web Assembly.  JS has no real integer support except of the asm.js-style latent/sort-of-fragile sort, BigInt doesn't change that, but Web Assembly is sort of specifically designed to provide it.  If constant time operations are desired for crypto, adding Web Assembly instructions for them, that we as compiler/implementer can _guarantee_ are constant time, seems relatively easy (as long as the underlying architecture/CPU gives us the instructions to do it), and a much better fit than using plain JS.

**Comment by tschneidereit** [comment]
> And as far as crypto goes -- if we are going to actively attempt to enable and offer good support for having user-defined crypto operations, I think this is worlds better addressed in Web Assembly.

I agree with this, and there is active research in this direction, see e.g. [this short paper](https://cseweb.ucsd.edu/~dstefan/pubs/renner:2018:ct-wasm.pdf) by a group at UCSD.

**Comment by ekr** [comment]
> @ekr BigInt is arbitrary sized integers. Ain't gonna be doing constant time algorithms on arbitrary sized integers.

Yes, I know what BigInt is. Why are you saying we won't have constant-time algorithms? This is a pretty standard practice in cryptographic libraries. Perhaps you're thinking that you won't have constant-time algorithms because the running time of the algorithm depends on the size of the integer? Fortunately, for PKC, you typically know the size (it's <= some modulus) and so you're only concerned that all numbers in the range perform identically.

I'm not suggesting that we should be attempting to enable support for user-defined crypto operations. I am saying that if we provide BigInt, then people will use it for crypto whether we want them to or not, and if it's not constant-time, that's a hazard.

**Comment by jswalden** [comment]
@ekr Yes, I meant because "depends on the size of the integer".

Why would we have constant-time algorithms for fixed-size integers?  The natural implementations for many operations likely will involve some internal loops of argument-dependent size. (I'm generalizing from limited experience in the bigint code in SpiderMonkey's dtoa, could be I'm mistaken.)  I think we'd have to deliberately go out of our way to provide constant-time operation.  And given that initially we would be embedding libgmp's implementation (which I can't imagine tries to provide constant-time operations), constant time operation is not something we would provide.

I think it's perfectly reasonable to tell people implementing their own crypto operations using BigInt "don't do that".

**Comment by ekr** [comment]
> @ekr Yes, I meant because "depends on the size of the integer".

Yes, this is not the sense in which people care about constant-time.


> I think it's perfectly reasonable to tell people implementing their own crypto operations using BigInt "don't do that".

You can tell people whatever you want, but my experience is that they are not very good about following it, and then you get problems.

**Comment by jswalden** [comment]
@ekr Sorry -- meant something more than "depends on the size of the integer", also the width of bits set in the number.  In SpiderMonkey's dtoa, the BigInt code works by encoding numbers as an exponent `k`, an unsigned integer `x`, and `x` number `uint32_t` for the bits of the number.  Even for some maximum binary magnitude, numbers closer to zero will have smaller `x`, and so numbers of fewer binary digits will have generally faster operation time.  This doesn't seem like a completely esoteric implementation.

As to people not following directions, sure.  I don't see any alternative to this, if BigInt is deemed otherwise worthy of implementation.

**Comment by littledan** [comment]
Note, the JSC implementation is being done as part of an internship with Igalia, not Apple.

**Comment by ekr** [comment]
@jswalden: yes, it's  this kind of algorithm which you want to be constant time for cryptographic software. I agree that the implementation you want to get that isn't necessarily the natural one, though I'd note that it's also the case that such software doesn't generally have a lot of zeroes in the low order bits because then you're probably wasting bits.

**Comment by annevk** [comment]
https://github.com/tc39/proposal-bigint/issues/45 suggests TC39 at least is aware this is not suitable for cryptography. https://github.com/tc39/proposal-bigint/issues/53 however suggests developers are not and not much was done there to dissuade them from that fact.

**Comment by tschneidereit** [comment]
> Note, the JSC implementation is being done as part of an internship with Igalia, not Apple.

Ah, I'd misunderstood your comment on this last week - thank you for the clarification.

**Comment by tschneidereit** [comment]
@ekr, can you expand on the shape of the footgun you see here? I could see two different issues:
1. Someone would've implemented some crypto algorithm in JS no matter what, but now they use BigInt, increasing the bandwidth of the timing side channel.
2. Someone sees BigInt and decides that this makes it feasible for them to implement some crypto algorithm in JS where otherwise they just wouldn't have.

For 1), I'm skeptical that BigInt changes much: writing constant time code in JS is hard to impossible without BigInt already, so this would only matter if the timing channel's bandwidth increased massively with the introduction of BigInt. Even then, I'd argue that this would only be relevant when comparing naive implementations: I find it highly unrealistic that someone with the expertise to minimize the timing channel's bandwidth in JS would just assume BigInt operations to be constant time without checking.

2) seems quite unlikely to me: people don't usually implement crypto systems in JS because they want to but because they don't have an alternative.

None of this is to say that we, including TC39, shouldn't do better on educating people about these issues. [The issue](https://github.com/tc39/proposal-bigint/issues/53) @annevk mentions certainly proves that much.

**Comment by ekr** [comment]
#2, and more specifically, rather than using a library where people have gone to real effort to avoid timing channels.

**Comment by annevk** [comment]
We could perhaps alleviate some of this if we restricted BigInt to secure contexts so folks wouldn't try to use them as an alternative to Web Crypto (and perhaps some further investment in Web Crypto is warranted to support newer crypto primitives).

**Comment by littledan** [comment]
We've talked about adding constant time operations for BigInts *in a particular range* to the BigInt proposal, as a standard library. This was delayed to "v2" as the current proposal is kept deliberately minimal.

https://github.com/mozilla/standards-positions/issues/65#issuecomment-376472641 and https://github.com/mozilla/standards-positions/issues/65#issuecomment-376479680 match my understanding of the issue. Since Numbers can already be used to "bypass secure context restrictions" in WebCrypto, I'm not really convinced BigInts make the problem worse enough to justify a secure context restriction on them.

JavaScript does not make any distinction between secure and insecure contexts. I raised the issue in https://github.com/tc39/ecma262/issues/1093 and TC39 was not very receptive to the idea. Given that Chrome may ship BigInt soon, including in insecure contexts, it seems like now would be the time for those in favor of secure context restrictions for BigInt to make a very clear case to TC39 to make this change.

**Comment by bzbarsky** [comment]
I would also strongly suggest that people with concerns raise them in Chrome's intent thread....

**Comment by jswalden** [comment]
@annevk There's strong opposition these days to subdividing the language -- and BigInt-by-context is subdivision -- for basically any reason.  Secure versus insecure context included.  (I'm not sure it does much anyway -- someone wanting a JS crypto library might well put it on their HTTPS site.)  Not to mention that distinction is non-existent outside browsers, and SpiderMonkey is also used outside browsers.  I agree investment in Web Crypto to obviate hand-implemented crypto on the web is good, tho that doesn't address the non-browser context -- wherefore, IMO, Web Assembly.

**Comment by adrianhopebailie** [comment]
Note to mention that BigInt is very useful in financial applications (possibly Web Payments API related?) in place of floating point numbers. Having it available in the platform alongside Web Payments API would be very useful.

Example: If BigInt was available I suspect that [`PaymentCurrencyAmount.value`](https://www.w3.org/TR/payment-request/#dom-paymentcurrencyamount-value) would have been defined as a combination of a `value` (as BigInt) and `scale` rather than a string.

**Comment by jswalden** [comment]
@adrianhopebailie I'm just repeating my general impressions from years in TC39 circles, not direct experience, but I had thought a decimal type was generally preferred for financial situations.  I know IBM was pushing on something like that a very long time ago; I don't know the status of anything like that offhand (and obviously it's not on point for _this_ RFP).  Just to say, I'm doubtful currency amount measurements are the best use case for this.

**Comment by adrianhopebailie** [comment]
> I had thought a decimal type was generally preferred for financial situations

It's not as black and white as that actually. 

Ideally you want a BigDecimal so that you can store both a magnitude and scale but it is sufficient to use a BigInt and express the scale separately. What you absolutely don't want to do is use floating point decimals which is why you'll see most financial applications use a String instead of a number.

**Comment by pcdinh** [comment]
BigInt support lands in Google's Chrome https://v8project.blogspot.com/2018/05/bigint.html

**Comment by ekr** [comment]
I continue to think this is going to lead to problems, so there really needs to be an aggressive warning in the standard and in other documentation, but I also agree that this is a valuable addition to the language, so I regretfully don't object to seeing it move forward.

**Comment by littledan** [comment]
@ekr PRs to the README are welcome. I don't see any docs in MDN, but that'd be another place to put such a warning. (BTW you might as well put a similar warning on the docs for Number and TypedArrays, as I'm sure people use those features for these purposes as well.)

**Comment by tschneidereit** [comment]
@littledan, I think MDN docs are probably the highest-value place to add this to, but we should also talk about where in the spec might be appropriate places. We can then see how best to coordinate getting that in place. Let's discuss at the next meeting in a couple of weeks.

**Comment by kaizhu256** [comment]
i'm beginning to have concerns on whether bigint is aligned with the needs of industry.  from what i can tell, there are 2 primary painpoints industry has in dealing with javascript-numbers:

1. loading/storing 64-bit integers over-the-wire to/from many popular databases (commonly via JSON).
2. decimal-arithmetic when handling money.

bigint only partially solves 1., and in a non-user-friendly-manner, in its attempt to expand its scope to arbitrary-precision numbers (which has no real industry use-case i'm aware of).  and its mostly impractical in addressing 2., when adopting a separate decimal128 datatype for javascript would make alot more sense to industry.

i think an additional criteria for stage-4 consensus on bigint is to get feedback from industry on whether its actually the best solution for solving real-world painpoints, like a need for standardized-ways to pass these values around via JSON.  i know its late in the game, but maybe we should also consider alternatives, like having 2 separate proposals instead for smaller-scoped BigInt64 and BigDecimal128 that could better meet the needs of industry.

**Comment by callahad** [comment]
This has been dormant for a year, and according to [Bug 1366287#c177](https://bugzilla.mozilla.org/show_bug.cgi?id=1366287#c177) we're on track to ship BigInt in Firefox 68... is that accurate, and are we fully supporting this proposal?

**Comment by jswalden** [comment]
We've implemented this.  Barring some unanticipated catastrophe exceeding simple and fixable bugginess, we're shipping it.  That's supporting it, "fully" if you really really need the extra non-intensifier.  :-)

**Comment by marcoscaceres** [comment]
Unrelated to this bug, we do have “important” as a position - but we really ought to have a “implemented”, “shipping”, or similar position. @dbaron, wdty?

**Comment by dbaron** [comment]
I think "shipping" is somewhat independent of our position.  We sometimes ship things with some reluctance because everyone else is doing it and we think it's at least not harmful... or even with more reluctance when we think it is harmful but we're forced to do so.

So the intent of the set of positions is to cover the space of what we think about it, independent of our decision to ship the feature which is influenced by other market factors such as compatibility and holding up the commitments we make in standards processes.

So even if we have implemented it, the position should say what we think about it.  I would probably characterize what I've seen in this issue as `worth prototyping`, i.e., something that seems likely to be a valuable addition to the web (while may have some issues, though probably unlikely to make it of net negative value), but at the same time isn't one of the central things we're pushing because we believe it's important for our users and our mission.

Or am I misreading the statements in this thread?
