### ISSUE TITLE
DisplayMediaStreamConstraints.surfaceSwitching

### ISSUE THREAD

**Issue by eladalon1983** [mozilla/standards-positions#653]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: DisplayMediaStreamConstraints.surfaceSwitching
* Specification or proposal URL: https://github.com/w3c/mediacapture-screen-share/pull/225/files
* Mozillians who can provide input (optional): @jan-ivar 

### Other information
The PR that introduced this new API surface was approved by @jan-ivar.

**Comment by jan-ivar** [comment]
`non-harmful` sounds appropriate, with the rationale that this API is a hint to be deprecated once [getViewportMedia](https://w3c.github.io/mediacapture-viewport/#dom-mediadevices-getviewportmedia) is widely implemented, something I recommend Mozilla implement instead of this.

As much as I think the "Share this tab instead" button in Chrome's [getDisplayMedia](https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia) is a nice feature, this API to turn it off seems like a workaround for e.g. the Google Docs+Meet integration using the latter (gDM) for lack of the former (gVM).

I think we should be open to switching it to `harmful` later if we see signs of user agents using this as a signal to focus their UX to drive users to pick self-capture, something that carries [inherent risks](https://blog.mozilla.org/webrtc/share-browser-windows-entire-screen-sites-trust/).

**Comment by bgrins** [comment]
Thanks @jan-ivar - that makes sense to me. @eladalon1983 are you the appropriate person to change our position on https://chromestatus.com/feature/5067650299330560?

**Comment by eladalon1983** [comment]
Thank you for the formal position. I have updated ChromeStatus.
