### ISSUE TITLE
Subset of CSP 3: script-src-elem, script-src-attr, style-src-elem and style-src-attr

### ISSUE THREAD

**Issue by evilpie** [mozilla/standards-positions#666]
## Request for Mozilla Position on an Emerging Web Specification

Specifically the CSP 3 directives `script-src-elem`, `script-src-attr`, `style-src-elem` and `style-src-attr`.

* Specification Title:  Content Security Policy Level 3
* Specification or proposal URL: https://w3c.github.io/webappsec-csp/
* Caniuse.com URL (optional): https://caniuse.com/?search=csp%20-src-
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1529337 https://bugzilla.mozilla.org/show_bug.cgi?id=1529338
* Mozillians who can provide input (optional): @evilpie @mozfreddyb 

### Other information

This has been implemented by Chrome and Webkit. The script-src-elem/attr is useful for creating different policies for event handlers and script blocks. We have seen at least one (now fixed) web compat issue by missing script-src support.

**Comment by bgrins** [comment]
Note there's a meta discussion happening on https://groups.google.com/a/mozilla.org/g/dev-platform/c/LlxUr3vIBWc/m/MEAfPhS5AAAJ about whether we should have one position request for all of CSP level 3 or one by one for each feature

**Comment by dveditz** [comment]
When it comes to HTML content-injection (including XSS) there is some difference between attributes and element injections. And in legacy sites it can be far easier to remove inline style and script blocks than to rework the site to remove inline style or event handler attributes. By splitting script-src and style-src into components this allows more sites to deploy stricter policies by limiting the use of 'unsafe-inline' even if it's not possible to fully remove it.

As part of these new directives, a new keyword `'unsafe-hashes'` was added to the specification. This instructs browsers to require hash matches for attributes that would otherwise require 'unsafe-inline', eliminating another case where people have needed to have a weak policy.  These hashes are considered "unsafe" and require this opt-in because these inline event handlers are typically short, and the hash match allows an attacker to inject an identical handler elsewhere on the page if that turns out to be useful.  There is some risk, but not nearly as much as allowing full 'unsafe-inline' abilities.

**Comment by dveditz** [comment]
The Firefox security engineering team fully supports these attributes.
