### ISSUE TITLE
ECMAScript Decorators

### ISSUE THREAD

**Issue by bennypowers** [mozilla/standards-positions#700]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Decorators
* Specification or proposal URL: https://github.com/tc39/proposal-decorators

### Other information

Decorators allow metaprogramming and composition patterns in object-oriented javascript code. They are a popular abstraction in many typescript-based and typescript-supporting frameworks. The Proposal recently reached stage 3 : candidate, and typescript is [updating their implementation](https://github.com/microsoft/TypeScript/pull/50820/files#). What is Mozilla's position on the standard?

**Comment by codehag** [comment]
Hi @bennypowers -- As you mention, Decorators are at stage 3 at TC39. We are quite involved in TC39 and comment on all proposals before they reach stage 3. If you are interested in our comments, you can review the notes. The most recent [notes](https://github.com/tc39/notes/blob/main/meetings/2022-03/mar-28.md#decorators-for-stage-3) where we commented was before this went to stage 3 as well as raising some of our concerns, for example regarding decorator metadata which we are now reviewing. You can read more about Mozilla's position on stage 3 TC39 proposals here: https://mozilla.github.io/standards-positions/#tc39-stage-3. If something has reached stage 3, it is because we have already reviewed and commented on it.

Is there a specific question that you have regarding this proposal? Otherwise, I will close this in line with our policy on TC39 stage 3 proposals.

**Comment by bennypowers** [comment]
No that's quite helpful, thanks.

**Comment by trusktr** [comment]
GitHub issue tracking all implementations:

- https://github.com/tc39/proposal-decorators/issues/476
