### ISSUE TITLE
Request for position: WebRTC RTP header extension control

### ISSUE THREAD

**Issue by fippo** [mozilla/standards-positions#713]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: RTCRtpTransceiver.setOfferedRtpHeaderExtensions()
* Specification or proposal URL:  https://w3c.github.io/webrtc-extensions/#rtp-header-extension-control
* Caniuse.com URL (optional): n/a
* Bugzilla URL (optional):  n/a
* Mozillians who can provide input (optional): @jan-ivar, @docfaraday

### Other information
This will help drive down some not-great SDP munging in Chrome.

cc @alvestrand

**Comment by docfaraday** [comment]
So, the gist seems reasonable, but I have a significant concern about the proposed execution; _w3c_ language is making normative alterations to an _IETF_ specification. By my understanding, this is flat out not allowed, and for good reason. I think that we get a much better result if we say something to the effect of 

> the phrase "each supported RTP header extension" in JSEP is defined by the [[HeaderExtensionsSupported]] slot

However, this still leaves us with the inability to reoffer an extension that was previously disabled, since JSEP categorically forbids reoffering header extensions that were not present in the previous answer, even if they are supported. For now, marking an extension "stopped" will have to be irreversible unless JSEP itself is revised over on the IETF side of things (maybe this is acceptable from a POLA standpoint because marking a transceiver "stopped" is also irreversible?). If we have a solid use-case for re-enabling a previously disabled header extension that is not solved by scrapping the RTCRtpTransceiver and making a new one, this might be worth doing, but I don't know whether we have such a use-case in mind.

**Comment by docfaraday** [comment]
After reading the explainer doc [here](https://docs.google.com/document/d/1y1hTsMeav5ijPvoqu1R6U4YC564i1QzgkMeIqWhgiis/edit#heading=h.o92j6jwzea4x), it seems that the use-cases would be satisfied with a simple |enabled| bit, as opposed to having a |direction| field. Are there use-cases for fine-tuning the direction?

**Comment by alvestrand** [comment]
I don't think this makes any normative change to an IETF recommendation; it only controls what each party offers. (JSEP is a bit of an oddity, in that it goes quite far into specifying things that are really in the *W3C* domain, but I digress.)

The reason for the "direction" rather than a simple bit is that the IETF spec for header extensions specifies that extensions can have a direction; I did not want to prevent Web apps from using that functionality, if it's useful.

The only case that I have been able to imagine using it is if an endpoint is capable of sending a particular extension, but wishes to announce that it can't handle receiving it (for instance a receive-mostly node that is capable of sending a congestion control signal, but doesn't have the logic to respond appropriately to the same congestion control signal of its own media, so the partner should select another mechanism. It seems a bit odd, but you never know.

**Comment by docfaraday** [comment]
> I don't think this makes any normative change to an IETF recommendation

It changes the text of JSEP, in a way that changes the mandatory behavior. That is by definition a normative change to JSEP.

**Comment by docfaraday** [comment]
> (JSEP is a bit of an oddity, in that it goes quite far into specifying things that are really in the _W3C_ domain, but I digress.)

Agreed. There is way too much leakage between the two specifications, making it a big headache to have a good abstraction layer between JSEP stuff and webrtc-pc stuff. But I suppose we're stuck with it. Let's just not make things worse by revising specifications from a different standards body.

**Comment by jan-ivar** [comment]
@docfaraday Is [this](https://www.rfc-editor.org/rfc/rfc8829.html#section-5.2.2) the line you're referring to? _"The RTP header extensions MUST only include those that are present in the most recent answer."_

As an observation, this API might still (be made to) work under those restrictions, e.g. ahead of initial negotiation, or after initial negotiation to remove more header extensions. It might be interesting to enumerate the use cases a stricter implementation like that would fail to satisfy.

**Comment by jan-ivar** [comment]
I've opened https://github.com/w3c/webrtc-extensions/issues/130 with one concern.

**Comment by docfaraday** [comment]
> @docfaraday Is [this](https://www.rfc-editor.org/rfc/rfc8829.html#section-5.2.2) the line you're referring to? _"The RTP header extensions MUST only include those that are present in the most recent answer."_
> 
> As an observation, this API might still (be made to) work under those restrictions, e.g. ahead of initial negotiation, or after initial negotiation to remove more header extensions. It might be interesting to enumerate the use cases a stricter implementation like that would fail to satisfy.

That is the line that forbids reoffering something that was previously disabled, yes.

**Comment by docfaraday** [comment]
Filed a couple of minor issues:

https://github.com/w3c/webrtc-extensions/issues/131
https://github.com/w3c/webrtc-extensions/issues/132

**Comment by fippo** [comment]
ping. Updated link:
https://w3c.github.io/webrtc-extensions/#rtp-header-extension-control
and issue title updated for the new name

**Comment by fippo** [comment]
As stated in https://github.com/w3c/webrtc-extensions/issues/134#issuecomment-1336450459 browsers do not care what JSEP does already and reoffer header extensions. This API is just a know for this.

**Comment by henbos** [comment]
Can we separate the question of whether or not you should be [allowed to restart stopped header extensions](https://github.com/w3c/webrtc-extensions/issues/134) which is a JSEP problem from the question of whether or not having this RTP header extension API is a good idea in the context of Chromium doing an Intent to Ship for this API?

The reason why I make this distinction is that "restarting stopped header extensions" is a feature that has been launched for several years via SDP munging and depended upon in the wild. Getting working group consensus on this, filing an intent to deprecate, and migrating existing uses is a long process.

The goal of the API is not to be able to do MORE than you can already do today, the goal of the API is to make it possible for people to stop SDP munging. Let's separate "stop SDP munging" from "stop re-adding extension". If we want to deprecate the latter, that is a problem we have to face with or without this API.

**Comment by henbos** [comment]
@jan-ivar @ekr @docfaraday

**Comment by henbos** [comment]
My interpretation from talking to Jan-Ivar is that having an API to control this rather than SDP munging is a good thing and most concerns have been addressed, but there is this one last issue with https://github.com/w3c/webrtc-extensions/issues/134 and the fact that we're overriding JSEP language.

Does this mean Mozilla is positive, negative, or mixed signals in the context of an I2S?

**Comment by docfaraday** [comment]
Broadly speaking, I think the rtp extension API is worth doing. I also think that it makes sense to revise JSEP to allow restarting a stopped extension, especially considering that this is what browsers seem to be doing anyway. I think that both of these are worth doing independent of one another.

**Comment by martinthomson** [comment]
So this issue covers only the extension negotiation piece, on which it sounds like we are positive.  I'll mark this issue as such and close unless I hear otherwise.

@docfaraday do you think that the JSEP revision/update is a necessary part of this work?  I'm reading that you are saying it is a separate piece of goodness.

**Comment by alvestrand** [comment]
Seems to me that reopening JSEP to align it with reality + experiences is a piece of goodness, but requires marshalling the will-to-work necessary to drive this through the IETF.

There are a number of places in webrtc now that extend or modify JSEP-documented procedures based on experience.

**Comment by ekr** [comment]
The first rule of holes is to stop digging. If the WebRTC WG wants to renegotiate the boundaries between the W3C and the IETF on this topic, it should do so. What it *should  not* do is continue to update JSEP in its own specs.

**Comment by docfaraday** [comment]
> So this issue covers only the extension negotiation piece, on which it sounds like we are positive. I'll mark this issue as such and close unless I hear otherwise.
> 
> @docfaraday do you think that the JSEP revision/update is a necessary part of this work? I'm reading that you are saying it is a separate piece of goodness.

From a spec perspective, this is essential to allow restarting stopped extensions, but the header extension control API is useful without that property. In that respect, they are separable. Also, there's the fact that browsers already allow restarting stopped extensions, which I guess you could argue makes this not super urgent. Still needs to be done though.

**Comment by docfaraday** [comment]
Filed https://github.com/rtcweb-wg/jsep/issues/1031

**Comment by martinthomson** [comment]
Marking this as positive, with the proviso that the IETF/W3C split be fixed.
