### ISSUE TITLE
Request for Position: Remove support for data: URL in SVGUseElement

### ISSUE THREAD

**Issue by shhnjk** [mozilla/standards-positions#718]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Remove support for data: URL in SVGUseElement
* Specification or proposal URL: https://github.com/w3c/svgwg/pull/901
* Mozillians who can provide input: @mozfreddyb

### Motivation
Assigning an attacker controlled string to `SVGUseElement.href` causes XSS due to data: URLs. This also led to a [bypass of Trusted Types](https://github.com/w3c/trusted-types/issues/357) in Blink.

Since Webkit does not support data: URLs in SVGUseElement and @mozfreddyb's [interest in unshipping](https://github.com/w3c/trusted-types/issues/357#issuecomment-1049761361), we think that it worth unshipping in Blink. 

Therefore, we'd love to get official signal from Mozilla.

Currently, the [usage](https://chromestatus.com/metrics/feature/timeline/popularity/4356) of data: URLs in SVGUseElement is about 0.0056% of page load in Chrome.

**Comment by shhnjk** [comment]
Great, thanks!

**Comment by emilio** [comment]
Not opposed, but how are data uris more dangerous than any other arbitrary cross-origin URI?

**Comment by emilio** [comment]
I guess the idea would be that other cross origin requests won't ever be allowed either?

**Comment by shhnjk** [comment]
> I guess the idea would be that other cross origin requests won't ever be allowed either?

It's already [specified](https://svgwg.org/svg2-draft/struct.html#UseElementHrefAttribute:~:text=In%20particular%2C%20this%20specification%20does%20not%20allow%20cross%2Dorigin%20resource%20requests%20in%20%E2%80%98use%E2%80%99.) as not allowed in the spec.

**Comment by SebastianZ** [comment]
Just to provide a use case for cross-origin requests: I recently had the need to re-use an external SVG multiple times within a document and style them individually.

This only works via `<use>`. Though all images on that site are normally coming from a CDN. And because cross-origin requests are currently not allowed, I had to deliver them via the same domain instead.

If SVG obeyed to CORS, this wouldn't be an issue.

And there could also be some CORS header that controls whether `data:` URLs are allowed in SVG. So, restricting them by default, yes, but authors would still have a way to opt-in to support them.

Sebastian

**Comment by mozfreddyb** [comment]
So far, we have relied on your assessment of feasibility. We have not done any specific explorations for our user base and doing so for our release population would take some time and work.

If there is a simpler route, we are open to exploring the possibilities for something simpler. The thread mentions a restriction on script elements, but we would also have to take care of other script capabilities like event handlers and such.

**Comment by RByers** [comment]
Thanks. Sorry, what I meant by "simpler" is that I think we all feel that disallowing data URLs is the architecturally cleanest option and also most likely to lead to cross-browser interop given Safari's lack of support already. So we're working to push ahead with that and chromium is willing to take some non-trivial compat pain for it. So that's still our "simplest" preference assuming we can make it stick in Chromium and Gecko can follow. But if it appeared unlikely Gecko would be able to follow chromium in making this breaking change, then we'd probably want to revisit the more complex alternatives like blocking script execution in that context.
