### ISSUE TITLE
Web Budget API

### ISSUE THREAD

**Issue by Jxck** [mozilla/standards-positions#73]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web Budget API
* Specification or proposal URL: https://wicg.github.io/budget-api/

### Other information

* Google Blog: https://developers.google.com/web/updates/2017/06/budget-api
* Origin Trialed: https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/completed-trials.md
  * First available in Chrome M60. Trial ended on October 17, 2017.
  * Feature team currently considering the next steps for the feature.

**Comment by martinthomson** [comment]
Having spoken to @beverloo about this, it seems like this is something that Google plan to decommission.  As I noted in [my feedback](https://discourse.wicg.io/t/proposal-budget-api/1717/7?u=martinthomson), there are simpler approaches to this, and Google are interested in exploring those further.

I don't think that this is harmful in the sense that this would damage the web ecosystem - at least any more than any other useless addition to the platform would be detrimental - so I think that "non-harmful" is what we should signal.

**Comment by dbaron** [comment]
Sorry for missing the pull request here for a bit.

I guess I'm fine with the `non-harmful` label, although:
* it seems like the use cases address real needs, but
* on the flip side, I'd be a little worried that the API might overly constrain implementations simply because they'd be forced by uses of the API to adopt the same policies as the implementation that the developers were targeting.  (This might be avoidable by carefully specifying what the budget numbers mean in a way that's more likely to lead to interoperability across different policies, but I don't think the current draft specifies it very carefully.)
