### ISSUE TITLE
MathML colspan attribute for the `<mtd>` element

### ISSUE THREAD

**Issue by fred-wang** [mozilla/standards-positions#743]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: MathML Core  (mtd@colspan)
* Specification or proposal URL: https://w3c.github.io/mathml-core/#entry-in-table-or-matrix-mtd
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1814346
* Mozillians who can provide input (optional): @emilio 

### Other information

MathML 3 has an attribute called `columspan` [1] that is implemented in Firefox relying on the implementation of HTML's `colspan` attribute [2].

MathML Core instead switches to `colspan` for consistency with HTML [3] and clarifies things like parsing. In particular this makes things confusing for users who are familiar with HTML and can simplify implementation a bit (because of the name mismatch, we have to do some remapping to `colspan` or checks on element type in [2]).

Would Mozilla be interested in supporting this name (together with the legacy name `columnspan`)?

[1] https://www.w3.org/TR/MathML3/chapter3.html#presm.mtdatts
[2] https://searchfox.org/mozilla-central/search?q=columnspan&path=&case=true&regexp=false
[3] https://w3c.github.io/mathml-core/#entry-in-table-or-matrix-mtd

**Comment by zcorpan** [comment]
Is the intent that both `colspan` and `columnspan` be supported? The spec only mentions the former, which signals that `columnspan` should not be supported, but above you say "(together with the legacy name `columnspan`)".

I'm not convinced that renaming this attribute is worthwhile, especially if we end up with two attributes (need to handle what should happen if both are specified).

**Comment by fred-wang** [comment]
The idea is to deprecate and then remove `columnspan` in the future, but this will take more time.

**Comment by zcorpan** [comment]
OK. I think supporting both attributes is worse than the status quo, both for implementation complexity and confusion for web developers. By shipping support for both and hoping that the old name can be removed in the future we risk to stay in the state forever. I would be OK with changing the name if support for the old name can be removed at the same time.

For authors, if they with to support both legacy and new UAs would have to use both attributes, or rewrite to the old name with JS if the new name is not supported. https://w3c.github.io/mathml-core/#dom-and-javascript seems to define an empty interface for `MathMLElement`, and no specific interface for `mtd`. Is the plan to specify interfaces for elements that have element-specific attributes, so that support for attributes can be detected in JS?

**Comment by fred-wang** [comment]
There are some discussions about adding IDL for some MathML elements for example https://github.com/w3c/mathml-core/issues/166 ; but I guess for mtd this is on hold until the columnspan/colspan situation is clarified.

If Mozilla is not interested in supporting both attributes for a while, the alternative would be for authors to support both attributes and then rely on counters to check usage of columnspan without colspan before moving to the new name.

**Comment by emilio** [comment]
FWIW I we've been successful in removing other old mathml features in the past. I think the right way to go around this is adding a flag + use counter in Firefox, and see if usage is low enough to get away with removing it. If it is, then removing it at the same time we rename it to colspan seems fine.

**Comment by zcorpan** [comment]
I discussed with @hsivonen and we think it's not a good idea to rename existing MathML attributes in general (except to change namespaced attributes into no-namespace attributes). There's very little benefit, which makes the cost/benefit or risk/benefit hard to motivate.
