### ISSUE TITLE
Request for Mozilla Position on User Locale Preferences

### ISSUE THREAD

**Issue by romulocintra** [mozilla/standards-positions#751]
## Request for Mozilla Position on User Locale Preferences

* Specification Title: User Locale Preferences 
* Explainer URL: [Explainer](https://github.com/romulocintra/user-locale-client-hints#explainer--user-locale-preferences)
* Mozillians who can provide input : @dminor 

## Introduction

*"Find a reliable way to access user OS preferences to craft a better user experience, and improve accessibility over the web"*

User preferences are often system-wide settings (such as in Android, macOS, or Windows). Operating systems allow the user to specify custom overrides for settings such as:

  * Hour cycle (24-hour or 12-hour time)
  * Calendar system
  * Measurement unit preferences (metric or imperial)
  * Date/time patterns
  * Number separators (comma or period)

However, there’s currently no reliable way to access this information from the Web Platform to help craft better user experiences. Allowing web developers to access this information would allow them to improve the accessibility and usability of their websites, and bring the user experience of web applications closer to that of native applications.

- [Read the complete Explainer](https://github.com/romulocintra/user-locale-client-hints#explainer--user-locale-preferences). 
- [Slide Deck About User Locale Preferences](https://docs.google.com/presentation/d/1REfjL8HBfAQQoXzG69kk43ywuT2hW5SuJCNtYxWPAJk/edit?usp=sharing)

## Feedback 

I welcome feedback in this thread, but encourage you to file bugs against 

- [Explainer repository](https://github.com/romulocintra/user-locale-client-hints/issues).
- [WICG Thread](https://github.com/WICG/proposals/issues/78)

**Comment by martinthomson** [comment]
I'd like to see a more thorough analysis of the fingerprinting exposure.  There is a claim that "this information may or may not already be available to a certain extent to such services, based on the host and the user’s settings".  That is not particularly useful in determining whether the API makes the fingerprinting situation worse, better, or the same.  On face value, the large number of hints here seem likely to make the situation worse.

On the whole, we expect new work in these areas to find ways to reduce options for fingerprinting.   @hsivonen points out that this is particularly relevant here because the information being exposed is not configured by the user in the browser, but in system preferences.  It is not necessarily obvious to a user that their actions there will have this effect on what their web browser tells the sites they visit.

Then there is the extremely verbose nature of the client hints.  "Sec-CH-Locale-Preferences-numberingSystem" is an awful lot of bytes to send.  I see 13 (!) fields of similar length.  That many bytes is highly likely to inflate requests to the extent that it will have a significant effect on performance. Even HTTP/2 compression cannot eliminate that much extra data.

**Comment by romulocintra** [comment]
> I'd like to see a more thorough analysis of the fingerprinting exposure. There is a claim that "this information may or may not already be available to a certain extent to such services, based on the host and the user’s settings". That is not particularly useful in determining whether the API makes the fingerprinting situation worse, better, or the same. On face value, the large number of hints here seem likely to make the situation worse.
> 
> On the whole, we expect new work in these areas to find ways to reduce options for fingerprinting. @hsivonen points out that this is particularly relevant here because the information being exposed is not configured by the user in the browser, but in system preferences. It is not necessarily obvious to a user that their actions there will have this effect on what their web browser tells the sites they visit.
> 
> Then there is the extremely verbose nature of the client hints. "Sec-CH-Locale-Preferences-numberingSystem" is an awful lot of bytes to send. I see 13 (!) fields of similar length. That many bytes is highly likely to inflate requests to the extent that it will have a significant effect on performance. Even HTTP/2 compression cannot eliminate that much extra data.

H @martinthomson , thanks for your feedback, we are dropping the extensive list of data and trying to encapsulate that information using [ buckets that ](https://github.com/romulocintra/user-locale-client-hints/pull/8/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R190)reproduce more or less the current OS preferences regarding Language & Region Date & Time and those would be under the "privacy gates" from each host. Do you see any different approach or strategy that might help?

**Comment by hsivonen** [comment]
(How come there doesn't appear to be a URL for the rendered spec?)

The main problem here is that core values of i18n and privacy are in conflict: To make the Web adapt better to the preferences who are in a minority context for i18n purposes, people in the minority context become more trackable across the Web or, even ignoring cross-site aspects, identifiable as belonging to a minority. (By context that I mean that how distinctive a given set of preferences is depends on what's typical for the the region to which the server-visible IP address geolocates to.) As noted, that the preferences are set on the system level makes this even more problematic, since a pref that appears to be for the local system would have privacy implications on the Web.

People might have different priorities, and if the user is asked explicitly, that sets a bar for how useful the feature needs to be. Are these preferences important enough that an explicit authorization prompt wouldn't be considered a larger negative than the positive of knowing the preference values?

It would be worthwhile to consider to what extent the use cases could be addressed by browser-rendered elements. For example, if the site renders a date picker with a month view with rows for weeks, it’s relevant to know what the user considers to be the first day of the week. 

As noted, the HTTP flavor of exposing this information is excessively verbose.

Furthermore, how would the dynamics differ from the precedent of Google Search ignoring Accept-Language? (See the link below for elaboration.)

(While preparing this comment, I made more verbose notes. I’ll post these on the [WICG issue](https://github.com/WICG/proposals/issues/78) as they seem more appropriate there than here.)

**Comment by romulocintra** [comment]
> (How come there doesn't appear to be a URL for the rendered spec?)

https://romulocintra.github.io/user-locale-client-hints

**Comment by hsivonen** [comment]
This was superceded by #844. I recommend closing this one.
