### ISSUE TITLE
RFP: Improving Ergonomics Of Events With Observable (WHATWG)

### ISSUE THREAD

**Issue by benlesh** [mozilla/standards-positions#76]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Improving Ergonomics Of Events With Observable
* Specification or proposal URL: https://github.com/whatwg/dom/issues/544

### Other information

This is a proposal from Google with interest on the part of the Chrome team to add the Observable type to the browser as part of the `EventTarget` API. It is loosely related to the [TC39 Observable proposal](https://github.com/tc39/proposal-observable), where it was determined that they would like to see it's usefulness demonstrated as part of the platform.

**Comment by annevk** [comment]
As I mentioned on Twitter, In https://github.com/whatwg/dom/issues/544#issuecomment-361339775 @bzbarsky asked for a processing model description that hasn't been provided yet. That would be good to have.

@tschneidereit should look at this too and maybe @wanderview.

**Comment by simonbuchan** [comment]
Not a rhetorical question: I'm not quite sure what level of detail is being asked past what is in the proposal and in the reply to that comment immediately after it was asked?

The proposal definitely is pretty loosely worded in it's semantics, e.g. `Observeable.of` simply says

> The values are delivered synchronously when `subscribe` is called.

but unless you're already familiar with observables it's not immediately clear that that has to mean something like:

```js
Observable.of = (...items) => {
  return new Observable(subscriber => {
    for (const item of items) {
      subscriber.next(item);
    }
  };
}
```

that is, when you call `.of(1,2,3).subscribe(console.log)`, you get the three calls to `console.log` before `subscribe` returns.

The further details of how other observable behaviors work is entirely up to them: the protocol is more a set of limits on what it is permissible for something calling itself an observable\* to do, more so than `Promise` for example, where there's only really one way to meet the described behavior.

That said, there's still a lot of exact details, for example what happens when an error is thrown in a subscriber's `complete` handler, etc.., but those all have proposed standardese in the `spec` dir, viewable in [the github repo summary link](https://tc39.github.io/proposal-observable/).

On the other hand, there's still plenty of discussion around the API for observables, e.g. RxJS 6 moving entirely to `.pipe()`ing loose operators, the existence  so I'm not saying this proposal is ready be pushed forward yet, but I'm not seeing those discussions happening at the moment. 

\*  not to be confused with the `Observable` constructor, which is really a helper to easily create valid observables, similarly to `Promise` not really being required to make a promise-like that will work with other promise-likes

**Comment by annevk** [comment]
Closing this as there hasn't been much follow-up. Once there's renewed interest and a processing model, we'd be happy to evaluate.
