### ISSUE TITLE
Request for position: COEP violation (Reporting API) 

### ISSUE THREAD

**Issue by sefeng211** [mozilla/standards-positions#796]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: COEP violation Reporting 
* Specification or proposal URL (if available):  https://html.spec.whatwg.org/multipage/browsers.html#queue-a-cross-origin-embedder-policy-inheritance-violation
* Mozillians who can provide input (optional): @zcorpan

**Comment by zcorpan** [comment]
This is supported in both Chromium and WebKit (since Safari 16.4).

Reporting for COOP and COEP is useful to be able to enable cross-origin isolation and know what breaks for users without actually breaking (with report-only).

I'm not aware of privacy concerns here.

A relevant open spec issue is https://github.com/whatwg/html/issues/5328 where it looks like progress is made in https://github.com/w3c/reporting/pull/258

Suggested position: positive

**Comment by sefeng211** [comment]
Yeah, positive sounds good. 

I just resolved https://github.com/mozilla/standards-positions/issues/795 without adding an entry, I think it's fine? Can we close this as well?
