### ISSUE TITLE
WebAuthn PRF extension

### ISSUE THREAD

**Issue by agl** [mozilla/standards-positions#798]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebAuthn PRF extension
* Specification or proposal URL (if available): https://w3c.github.io/webauthn/#prf-extension
* Explainer URL (if available): https://github.com/w3c/webauthn/wiki/Explainer:-PRF-extension
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): dveditz

(Requested as part of https://groups.google.com/a/chromium.org/g/blink-dev/c/iTNOgLwD2bI)

**Comment by thecodrr** [comment]
Any update on this?

**Comment by WIcheese** [comment]
This is important.  Going "passwordless" is supposed to be the goal of passkeys.  Many things that are end-to-end encrypted, where the service provider doesn't have the ability to decrypt data, depend on the password to derive cryptographic keys client-side.  Passkeys can't replace passwords for end-to-end encrypted services if you can't also derive a consistent key for end-to-end encryption from them.  This extension is needed for that.

**Comment by Hemmingen** [comment]
See also: https://bitwarden.com/blog/log-into-bitwarden-with-a-passkey/
"Currently, browsers based on Chromium, such as Google Chrome and Microsoft Edge, support PRF WebAuthn." (January 11, 2024)
We need Firefox as an alternative to those browsers especially when it comes to password managers.

**Comment by jschanck** [comment]
I'm supportive of this extension. There was some [discussion](https://github.com/w3c/webauthn/issues/1462) of alternative approaches in 2020. However, there are several clear and beneficial use cases for the PRF extension, and the implementation cost is low. I also see no technical flaws in the proposal. Suggest `positive`.

**Comment by thecodrr** [comment]
I implemented PRF using Google Chrome as a test platform in [Notesnook](https://notesnook.com/) and I must say, the user experience is very seamless and secure. Would love to see this in Firefox & Safari for broader compatibility.

**Comment by LeanderGlanda** [comment]
It would be great if Firefox supported this. My plan is to go passwordless with Bitwarden and Passkeys.

**Comment by pmalek** [comment]
@martinthomson I understand that this has been accepted and is planned to be implemented? Can you point us to some links/issues where we can track the progress of this?

Very much looking forward for this feature!

**Comment by tcmal** [comment]
@pmalek The tracker for this particular feature is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1863819). It's part of [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1802863) larger task for some related standards.

**Comment by bernhardkaindl** [comment]
@jschanck (JFYI: @pmalek | @martinthomson | @thecodrr | @agl )

See https://levischuck.com/blog/2023-02-prf-webauthn as a demonstrator test site for testing the PRF extension implementation!

The verbose explanation and the intermixed code on the page may help to understand what needs to be implemented and the site can be used for testing. It is functional with Chrome.

Testing the Registration: https://levischuck.com/blog/2023-02-prf-webauthn#heading-registration

Using Chrome, clicking the button "Register" opens the registration of a username for this demonstration site. If the Bitwarden extension is enabled, the passkey is registered (saved) by the Bitwarden extension (otherwise by Windows Security using a device or Windows Hello).

Testing the Authentication: https://levischuck.com/blog/2023-02-prf-webauthn#heading-authenticate

Using Chrome, clicking the button "Retrieve PRF" opens the confirmation of using the passkey to authenticate with the demonstration site. If the Bitwarden extension is enabled and the passkey for the site is registered, the the Bitwarden extension offers to confirm the passkey, otherwise by Windows Security should do the same using a device or Windows Hello.

This is where I see that PRF is requested in the options `navigator.credentials.create(options);` for user registration using PRF in the example code shown on the site:
```js
    // Important part: the extensions!
    extensions: {
      // WebAuthn uses the same structure for registration
      // as authentication.
      // While it looks like we are asking the authenticator
      // to evaluate a PRF over the salt, this is more
      // of a not equals null, not empty check that sets
      // the authenticator up for future PRF use.
      prf: {
        eval: {
          first: state.salt,
        },
      },
```

The answer if PRF is supported is then checked in the code here:
```js
// See if PRF is supported or not
const extensionResults = regCredential.getClientExtensionResults();
if (extensionResults?.prf?.enabled) {
  state.prfSupported = true;
} else {
  state.prfSupported = false;
}
```

The `prf` key like for registration is also used when asking for authentication using PRF by `navigator.credentials.get(options);`:
```js
// Ask the browser to find and authenticate with the selected credential
const authCredential = await navigator.credentials.get(options);
```

For PRF, `navigator.credentials.create()` and `navigator.credentials.get()` would hav to talk to the authentication extension (like Bitwarden or Windows Hello) for saving (registering) the passkey and for confirming authentication at the site using the passkey.

I guess that the interfacing from to authentication extension should already be implemented for WebAuthn without PRF, so (I guess) hopefully, only the addition of authentication using PRF needs to be added.

Are these preconditions in place so this can be implemented?

**Comment by bernhardkaindl** [comment]
In the Chromium PRF ticket at https://issues.chromium.org/issues/40140659#comment21, this test suite was used: It has 3 different PRF buttons and the buttons report the test result: https://securitykeys.info/ts/test_suite.html

Another PRF test app: https://passkeys.fission.app/register
And here is the initial Passkeys ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1792433

**Comment by Ordiel** [comment]
I got here trying to get Firefox to use my yubi key for quite some time... installed chrome and it _just worked_.... sad. Bye mozilla in general, was good while it lasted

**Comment by saikotek** [comment]
Hopefully this gets implemented soon, as this is a really convenient feature.

**Comment by mghmay** [comment]
+1 hope this gets implemented soon, my browser of choice is Firefox but if I can't use my yubikey I might have to go back to silly old chrome

**Comment by gurgl** [comment]
I want my Yubikey to work with my favorite browser

**Comment by yeahthegoys** [comment]
Jesus H Christ. And you idiots wonder why nobody uses firefox. Long standing user frustrating bugs dont get fixed, and features people are asking for, which you have openly admitted are easy to implement, are just ignored outright. Genuinely embarrassing. I cannot recommend this browser to anyone, even though I dislike chromium more.
