### ISSUE TITLE
Isolated Web Apps

### ISSUE THREAD

**Issue by reillyeon** [mozilla/standards-positions#799]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Isolated Web Apps
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/WICG/isolated-web-apps/blob/main/README.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This proposal provides a way to build applications using web technologies that will have useful security properties unavailable to normal web pages. To enable stronger security these applications are packaged into Web Bundles, signed by their developer, and distributed to end-users through one or more of the potential methods described in the explainer.

The explainer is divided into 4 documents:

* The [main explainer](https://github.com/WICG/isolated-web-apps/blob/main/README.md) covers the overall goals of the proposal.
* The [scheme explainer](https://github.com/WICG/isolated-web-apps/blob/main/Scheme.md) covers the design of the proposed isolated-app:// scheme.
* The [permissions explainer](https://github.com/WICG/isolated-web-apps/blob/main/Permissions.md) covers an addition to the Web Application Manifest which allows a minimum Permissions Policy to be applied to the entire application.
* The [updates explainer](https://github.com/WICG/isolated-web-apps/blob/main/Updates.md) covers how applications will be updated.

This proposal will feel familiar to Mozillians who worked on the FirefoxOS project. There’s been good discussion on https://github.com/WICG/isolated-web-apps/issues/10 about lessons learned from packaging apps for FirefoxOS.

I have requested a TAG review at https://github.com/w3ctag/design-reviews/issues/842.

**Comment by robbiemc** [comment]
FYI, Chromium is rolling out an implementation of this proposal in a limited fashion (admin-controlled installation for managed users on ChromeOS devices). See https://groups.google.com/a/chromium.org/g/blink-dev/c/iMfYonTs414.

**Comment by martinthomson** [comment]
Hi Reilly, thanks for opening the discussion on this problem.  Our view here more or less matches that of [the TAG review](https://github.com/w3ctag/design-reviews/issues/842#issuecomment-1989631915) (yep, I get to say the same thing with two different hats on).  We don't think that this is the right approach to take overall.  

The way that the Web has been most successful in delivering new capabilities is not by removing the safeguards, but by finding safe ways to achieve goals.  To use one of your prime examples, if that means an end to direct use of TCP sockets, such that the server end has to adapt, that's something we've been willing to accept.  Mozilla made a serious attempt to build that sort of API in the past, but we've come to appreciate that the hazards involved in that approach far exceed the benefits.

This approach basically says that asking for those concessions on a case-by-case basis is infeasible. That opens up a bunch of risks with no real prospects for targeted mitigation, only a very general one.  Taking on those risks is unnecessary and potentially damaging.

**Comment by HughIsaacs2** [comment]
Wouldn't the argument against Isolated Web Apps shared here also apply to Web Extensions?

Why have Web Extensions if these risks exist?

**Comment by DemiMarie** [comment]
Would Mozilla still oppose this standard if it did not have bring any new capabilities to web applications _other_ than signed web bundles?

The reason I ask is that this proposal allows one feature that is currently impossible for web apps to provide, and that is end to end encryption secure against a malicious or compromised server.  This does not require _any_ new security risks — in fact, it is a pure security _benefit_.

**Comment by martinthomson** [comment]
Mozilla is working on a set of features that would allow for end-to-end encryption. Including compromised web servers in the threat model.  That does not involve Isolated Web Apps, nor does this proposal really help make E2EE more possible.  Those applications need things like [secure multiparty key exchange with MLS](https://datatracker.ietf.org/doc/html/rfc9420) and a suite of integrity and transparency features, not elevated privileges.

**Comment by DemiMarie** [comment]
Nevermind, I saw #29 and the same issues with that apply.

**Comment by reillyeon** [comment]
I eagerly await more details about the integrity and transparency features you mention. I'd like to re-iterate that the core IWA proposal (without the collection of IWA-only APIs that have also been proposed) does not grant elevated privileges, but is intended to provide an environment where it is _possible_ for the user agent to grant elevated privileges, or to run other workloads which require higher integrity and transparency without elevated privilege. However, I recognize that this particular proposal may be flawed and I am happy to see more proposals made in this area of research.

**Comment by bugeaud** [comment]
We have scenarios where we do need advanced features such as UDP socket and would be glad to have IWA permissions to enable that, but Mozilla's position -that I do understand to some extent- poses a threat to the web ecosystem, as the only alternative is again to bring a native application for some basic stuf like say communicate in UDP or with a TCP socket.

One scenario I got is simple : bring web to the home and SMA. Homes and SMA have multiple IP IoT and you need to manage them. People tend to get centralized here : think a small server. But if it crashes/dies, consequences can be huge. So in order to keep things simple and reliable people might want to be more decentralized as possible for the management. And as a start we need to be able to autodiscover the devices. Everything is there but you need to get UDP so you could get mDNS, find your machines and then working with them with the appropriate protocol, directly using web API & UI. Tomorrow we might need a way to authenticate in a secure way with IoT devices in a U2A or A2A scenario that will not rely on D|TLS and setting up a local PKI. IWA is a pebble on our path.

IWA is a way to recognize that in a closed environment (home or entreprise say) you might need more feature enabled than in public on internet. If your idea is to propose a way to get more feature for anyone (like the IWA API, including UDP & TCP sockets say), then this is fine but it will be even more challenging security wise. But if your idea is that such feature should never be provided then I think this is a problem as it damages the Web as a technology of the future.

**Comment by DemiMarie** [comment]
> or to run other workloads which require higher integrity and transparency without elevated privilege.

This is my use-case.  One cannot currently provide true end-to-end encryption via a web app because a compromised server can serve malicious JavaScript and tamper with or exfiltrate data.  Isolated web apps would allow this because only signed code is allowed access.
