### ISSUE TITLE
Request for Position: Device Attributes

### ISSUE THREAD

**Issue by sbykov-g** [mozilla/standards-positions#815]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Device Attributes API
* Specification or proposal URL: https://wicg.github.io/WebApiDevice/device_attributes/
* Explainer URL: https://github.com/WICG/WebApiDevice/blob/main/Explainer.md

**Comment by zcorpan** [comment]
Which use cases here are not solved through addons?

**Comment by sbykov-g** [comment]
This API is indeed copying our (chrome) existing extension API. But with a Web API our commercial customers won't have to develop/deploy a companion extension for their web apps.

**Comment by zcorpan** [comment]
OK. Since this API isn't intended for the web but for enterprise applications where IT admins have full control, it's arguably not part of the web and is therefore inconsequential for the web.

However, would it be possible to make the `managed` IDL attribute be entirely absent when the context is not a "highly trusted"? (Similar to `SecureContext`.) That would allow for feature-checking and reduce web compat risk, and avoid exposing a property to the web that does nothing.

**Comment by nightpool** [comment]
@martinthomson @zcorpan Hi all, I think there may have been some confusion here. This spec is taking what was _previously_ an addon-specific API and exposing it to the web platform. See https://github.com/w3ctag/design-reviews/issues/606 for more information and a previous TAG review of this that considered it harmful to the open web platform.

Based on the justifications given by the TAG previously, as well as other OS-dependent justifications (the five specified method calls seem to have been taken directly from how ChromeOS organizes their devices—it's unclear to me whether any other OS would be able to implement them), I would urge Mozilla to categorize this specification as harmful.

**Comment by zcorpan** [comment]
We understand that the proposal isn't for the addons/extensions context. Still, the API is defined to only work "when the web application is highly-trusted". Such apps are not the web and the API isn't exposed to web pages.
