### ISSUE TITLE
Origin Trials

### ISSUE THREAD

**Issue by theS1LV3R** [mozilla/standards-positions#859]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Origin Trials
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

First time requesting a position, unsure if this is even a standard google is trying to push.

Seems half way dead, as there is little activity in the repo both with commits and issues.

**Comment by zcorpan** [comment]
Origin Trials are supported in Chrome and also in Firefox.

https://developer.chrome.com/docs/web-platform/origin-trials/
https://wiki.mozilla.org/Origin_Trials

However, they're not a web standard. It's a mechanism for browsers to experiment with a new feature but only for a small number of origins that opt-in, so that the feature can still be removed or changed without breaking the web.
