### ISSUE TITLE
popover=hint

### ISSUE THREAD

**Issue by mfreed7** [mozilla/standards-positions#965]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: popover=hint
* Specification or proposal URL (if available): (slightly out of date as of 1/19/24) https://github.com/whatwg/html/pull/9778
* Explainer URL (if available): https://open-ui.org/components/popover-hint.research.explainer/
* Proposal author(s) (`@`-mention GitHub accounts): @mfreed7, @josepharhar
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This is related to, but not blocked/gated by, the [invokers proposal](https://github.com/mozilla/standards-positions/issues/902).

See also, https://github.com/whatwg/html/issues/9776.

**Comment by mfreed7** [comment]
Any thoughts on this one? There's now an [approved spec PR](https://github.com/whatwg/html/pull/9778) and a prototype implementation that seems to work nicely. We'd love to get implementer support.

**Comment by bramus** [comment]
It was recently announced that this is getting prototyped in Gecko: https://groups.google.com/a/mozilla.org/g/dev-platform/c/vaT1aQGETLM/m/XyjTUsHVBgAJ

**Comment by mfreed7** [comment]
> It was recently announced that this is getting prototyped in Gecko: https://groups.google.com/a/mozilla.org/g/dev-platform/c/vaT1aQGETLM/m/XyjTUsHVBgAJ

Given that this is being prototyped, would it be appropriate to say that Gecko is supportive of the API?

**Comment by zcorpan** [comment]
We've discussed this and we're positive. We have some reservations for `interesttarget`, but that is a separate proposal.

**Comment by jcsteh** [comment]
There is some great progress with regard to figuring out the accessibility story here as can be seen in the [accessibility section of the explainer](https://open-ui.org/components/popover-hint.research.explainer/#accessibility). However, I see some open questions there (e.g. what to do about a hidden details target) and I don't think we have a clear resolution on those. Furthermore, beyond the explainer, I don't see an ARIA pull request anywhere to formally spec the accessibility API mappings, though please let me know if I missed something. While I trust that these things will be addressed given the solid work so far, I do think the accessibility story needs to be finalised (and specified) before anyone considers shipping this to the web at large.

**Comment by mfreed7** [comment]
Thanks for marking this positive!

> There is some great progress with regard to figuring out the accessibility story here as can be seen in the [accessibility section of the explainer](https://open-ui.org/components/popover-hint.research.explainer/#accessibility). However, I see some open questions there (e.g. what to do about a hidden details target) and I don't think we have a clear resolution on those. Furthermore, beyond the explainer, I don't see an ARIA pull request anywhere to formally spec the accessibility API mappings, though please let me know if I missed something. While I trust that these things will be addressed given the solid work so far, I do think the accessibility story needs to be finalised (and specified) before anyone considers shipping this to the web at large.

I just wanted to acknowledge this comment and say that I agree on both counts. We need to update the explainer a bit, and we'll get an ARIA PR going also. Both good reminders, thanks! + @aleventhal to help me remember this. 😄

**Comment by scottaohara** [comment]
Discussed this today with @mfreed7 and @aleventhal.  I will get a PR going for HTML AAM to add popover=hint, but at this time we do not see it having any different mappings than `popover=auto` or `popover=manual`.  

Since there have been additional use cases for popover=hint, beyond just tooltips, and because - as noted in the explainer - popver=hint has nothing directly to do with hovering, appearing on focus, or other "interest" triggering, right now we think it's important to maintain the popover mapping status quo, and leave it up to authors to define the role and other aria-* attributes that are appropriate for what they're building.  

We do think, however, that this type of popover will be helpful in creating content that would be expected to appear on hover or focus, but that's where interesttarget would be relevant, and that attribute could then be used as the signal for further mapping updates.
